### ISSUE TITLE
apologise + ratio + stop? + its a music bot bozo

### ISSUE THREAD

**Issue by LidlBambi** [IMarkoMC/Tokens#10]

**Comment by IMarkoMC** [comment]
> apologise + ratio + stop? 

Open another issue with nonsense and you'll get banned from the repo

**Comment by IMarkoMC** [comment]
Nevermind, You already opened another issue after your first issue was closed.

Blocked. 
Have fun

**Comment by skidmaster69420** [comment]
Don't care + Didn't Ask + You are in debt + You suck + go fuck yourself + shitty music + token invalided + newb + scrub + get bent.

**Comment by Pabszito** [comment]
![cries-about-it-cry-about-it](https://user-images.githubusercontent.com/37744843/185771130-3008c6be-b4b6-41d9-ae6c-a31f870e6f57.gif)
