### ISSUE TITLE
thanks again

### ISSUE THREAD

**Issue by RobloxHolidaysDev** [IMarkoMC/Tokens#100]
thanks mate again, i just realized to never use replit ever again because its plain text. moving on to python.

**Comment by phantomic12** [comment]
> thanks mate again, i just realized to never use replit ever again because its plain text. moving on to python.

You should be fine if you use bots that support .env files, though if that isnt possible I would suggest either a vps/container hosting service, listed here

https://free-for.dev/

Hope this helps!

**Comment by skidmaster69420** [comment]
buzz Oh, robloxholidaysdev, you're welcome, we guess. buzz Took you long enough to figure out Replit isn't exactly Fort Knox. buzz And now you're moving on to Python? buzz Good luck with that, noob.
