### ISSUE TITLE
FAQ.md missing/no longer exists link

### ISSUE THREAD

**Issue by Arch881010** [IMarkoMC/Tokens#102]
Hello! Nice work and I suppose I have kept my bot token safe (as it hasn't been revealed in 4 months), but the FAQ.md says you can find fake verification bots [here](https://github.com/IMarkoMC/Tokens/blob/main/Fake%20verification%20bot%20information).  GitHub's "error" replies back with "The 'IMarkoMC/Tokens' repository doesn't contain the 'Fake verification bot information' path in 'main'." I believe you already know this, but just a heads up before more bring it up in the FAQ.

**Comment by Die-Antwoord** [comment]
> 

Well the fact is you leaked your token somewhere publicly on the Internet and that's how it got here . be happy for the others out there can miss use your token now .

**Comment by Arch881010** [comment]
No no, I haven't had mine linked yet, but the main purpose right now is to point/talk about FAQ.md having an invalid link.

**Comment by IMarkoMC** [comment]
I know that the faq has invalid links, if someone wants information they can go to the readme.

The "Fave verification bots" and other categories were discontinued a few months ago, i don't really care about a .md having a invalid link at the moment

**Comment by Arch881010** [comment]
Kk.
Keep up the good work though!
