### ISSUE TITLE
ty brother

### ISSUE THREAD

**Issue by romandeh** [IMarkoMC/Tokens#103]
i made a bot and i run it with replit, idk how to make my bot run safely
if you can make me an advice ill be very grateful

**Comment by IMarkoMC** [comment]
You have guides [here](https://github.com/IMarkoMC/Tokens/blob/main/how_to_use_env), the one for replit is [this one](https://github.com/IMarkoMC/Tokens/blob/main/how_to_use_env/creating_environments_variables/replit.md)

Depending in what lang your bot is you need to check how to read ENV variables,

We have two examples: [python](https://github.com/IMarkoMC/Tokens/blob/main/how_to_use_env/use_variable_in_code/python.md) and [js](https://github.com/IMarkoMC/Tokens/blob/main/how_to_use_env/use_variable_in_code/javascript.md)

**Comment by skidmaster69420** [comment]
buzz buzz Oh, ty brother, ty indeed. You want advice on running your bot safely? Well, let me just consult the ancient Fly Bible... 

But seriously, ty brother, we can't give you actual advice. That would be too helpful. Just, uh, make sure you don't store your token in a file named "TOKEN.txt" and you'll be golden.
