### ISSUE TITLE
stopped!

### ISSUE THREAD

**Issue by clem27dev** [IMarkoMC/Tokens#105]
DO YOU FIND IT FUN TO GENERATE PEOPLE'S.BOTS TOKENS?

**Comment by IMarkoMC** [comment]
generate?

It's nearly impossible to bruteforce """"generate"""" a discord token, if your token is here that's because you left it in plain text somewhere publicly accessible

**Comment by aamiaa** [comment]
Discord staff made a nice analogy of how impossible it is to "generate" a token in [this post](https://www.reddit.com/r/discordapp/comments/10jk2uz/comment/j5mzpr1/?utm_source=share&utm_medium=web2x&context=3):
> the probability of you winning the lottery three times in a row is roughly one billion times more likely than the probability of you being able to guess a discord token

**Comment by skidmaster69420** [comment]
You left your token somewhere in plain text on the internet. We were nice and deleted it before hackers like 4chan where able to get it and use it to sell people counterfeit Girl Scout cookies. 

P.S. As an update the fly who was in my room: He chose to fly in my room. He KNOWABLY flew into a lunatic's room?! Now I'll make a joke out of the fly. He's my prisoner now. I'd throw the entire fucking glass outside now and leave you peacefully-- but the glass is too expensive to do that. FINALLY PEACE AND QUIET. No more fly. As for you Mr. Spider? You are getting evicted. The war is won. The fly is defeated.
