### ISSUE TITLE
so basically I can't have a bot anymore because every now and then its token will get invalidated?

### ISSUE THREAD

**Issue by NeekoKun02** [IMarkoMC/Tokens#107]
I am not really into developing discord bots, but I still had time to code one for myself and my server. I'm 100% sure I never used it for anything suspicious apart from dismantling old server and setting them up point-blank. Now I get a notification that blocks every game I'm trying to play if I dont end discord in the task manager saying that the token was published... tf?

**Comment by IMarkoMC** [comment]
Store your token in ENV variables, you have guides in this repo.

Leaving your token in plain text can lead to your server being raided/nuked or your account termed because ToS violations

> now I get a notification that blocks every game I'm trying to play if I dont end discord in the task manager

If you executed some random game you might be infected with a stealer, check your OS or do a clean reinstall of discord.

**Comment by NeekoKun02** [comment]
Oh ok, ig I just left it in the code on replt months ago. Thank you mate

**Comment by skidmaster69420** [comment]
Glad that you had a happy ending to you issue after all! Thank you for flying IMarkoMC airlines. There are no refunds.

P.S. I once tried to mail myself in a box. But they won't let me. It's so fucking cheap. I fit into the box. The delivery guy will carry my 90kg ass, and delivery me. All he has to do is deliver my safely? It doesn't matter if I'm alive, as long as my body arrives their safely. If you buy a goldfish on the internet, it doesn't matter if it gets their alive. I mean if you think about it, isn't buying a goldfish off the internet like goldfish trafficking?
