### ISSUE TITLE
nice 

### ISSUE THREAD

**Issue by untouchaball73** [IMarkoMC/Tokens#108]
nice but is there any way to stop this from happening again?

**Comment by Die-Antwoord** [comment]
> nice but is there any way to stop this from happening again?

You should use .env you can read more here https://github.com/IMarkoMC/Tokens/tree/main/how_to_use_env

**Comment by skidmaster69420** [comment]
Please consider using env variables, a config file or a secret password written on the underside of a rock in your garden (where only you and your trusty neighbor Craig knows about.)

P.S. Flies don't sleep. This is liberal propaganda written by Big Mattress to sell more mattress. But when they do sleep, we must use this information to make it their LAST. I just found out there are these things called female horseflys. That BITE you. There is no concrete answer where they life. Isn't that a bit SUSPIOUS?!?!?!?!?!!!!!!!!!. If I meet any flying inspect other then a bee, I'll kill them. Bees are cute. Look at this fucker, isn't he cute? I hate them, but they look cute.
![image](https://github.com/IMarkoMC/Tokens/assets/108831945/54b1c19f-55ca-46f4-a875-6e83cd39708c)
