### ISSUE TITLE
L BOZO

### ISSUE THREAD

**Issue by DadLeftMeLOL** [IMarkoMC/Tokens#11]
L BOZO + GAY MONKEY LOOK AT U TRYNA EXPOSE BOT TOKENS

**Comment by Pabszito** [comment]
username checks out

**Comment by IMarkoMC** [comment]
Cry harder kid

**Comment by skidmaster69420** [comment]
Hello DadLeftMeLOL,

we at Skidmaster69420 LLC appreciate your issue. We also had our Token Voltures search for your dad! They found him, they told him about your existence. Upon which, your father called his fly department to contact our fly department. First off, we didn't know your father also ran a fly department! Anyhow, this is the request we got from him: "I literally don't want to pay child support leave me alone".  So then we had our fly department which also does the unpaid crying work for us, to cry for a solid 10 seconds. This was done in your honor. Anyhow... the flies don't like to go unpaid, unlike me who has an obsession with it. They demand 10.000 dollar for the crying they did in your name, think of it like a therapy bill, only much more affordable! So... yeah, here's the banking info of the fly department.

Bank: Fly Bank
Account: FlyAccount69420LLC

The amount is due in... oh sorry, it was due 9 days ago. You better watch out for angry flies. I am just an unpaid intern, I take no legal responsibility!

Yours
Unpaid Intern
Skidmaster69420 LLC
