### ISSUE TITLE
how did you get my token?

### ISSUE THREAD

**Issue by DeadManDeano** [IMarkoMC/Tokens#110]
I got a message from discord saying one of my bots tokens have been posted on the internet. To be honest I don't know what this token is and what it does but how do I prevent this from happening? 
my bot is a music bot which does what is says (provides music)

**Comment by Pabszito** [comment]
There are some tutorials [here](https://github.com/IMarkoMC/Tokens/tree/main/how_to_use_env) as well.

**Comment by skidmaster69420** [comment]
DeadManDeano, you're a music bot owner who doesn't know what a token is? That's like being a chef who doesn't know what a recipe is. Thanks for the laugh. And thanks, blackwolfwolf, for doing our job for us. We'll just add that to our FAQ: "Don't post your token publicly, duh."
