### ISSUE TITLE
among us 

### ISSUE THREAD

**Issue by DarthInfinix** [IMarkoMC/Tokens#111]
HOLY SHIT DID YOU JUST SAY THE WORD SUS???😳1?/1😱//1😳/1111!!!! Wait, you don't know what it is from?😳😳😳Let 👆give you a brief [r/history](https://www.reddit.com/r/history/). 📚📚📚👨‍🚀If you didn't [r/knowyourshit](https://www.reddit.com/r/knowyourshit/), the [r/term](https://www.reddit.com/r/term/) sus(suspicious) is a saying from the [r/popular](https://www.reddit.com/r/popular/) [r/game](https://www.reddit.com/r/game/) [r/AmongUs](https://www.reddit.com/r/AmongUs/). Among us is so fun😔 👉👈, don't insult it, every youtuber and streamer says so!!!!!!!11 Corpses voice is so deep am i right or am i right😳😳????? I mean Mr beast and Dream play and pull big 🧠 1000000000000 iq moves in their videos..... YOU WERE THE IMPOSTER.... ඞ ඞ ඞ Get it because you don't know what sus means? [r/stupidquestions](https://www.reddit.com/r/stupidquestions/) [r/youranidot](https://www.reddit.com/r/youranidot/) [r/stupidcuck](https://www.reddit.com/r/stupidcuck/). I CAnT BELEeVE YOUU dont KNoW WHT SUS MeaNS?/??!??!?!!🖕🖕🖕🖕🖕 Man why do i have to [r/explain](https://www.reddit.com/r/explain/) this to a [r/idiot](https://www.reddit.com/r/idiot/)🤪🤪🤪📚📚📚... Sus is a GREAT WORD from a GREAT VIDEO GAME. in class, YOU CAN PLAY IT ON YOUR PHONE😜😜😜😜😜😜**??!?!?** such a masterpiece... FOR THE GREAT PRICE OF FREE!!!11!💰💰🤑🤑🤑🤑😜😜😜💰💰 It can also mean gay 😳😳😳😳

**Comment by Die-Antwoord** [comment]
More salt for this one . . .

**Comment by IMarkoMC** [comment]
Taken care of
