### ISSUE TITLE
i love this repo

### ISSUE THREAD

**Issue by LewdHuTao** [IMarkoMC/Tokens#114]
you did a great job. i love seeing kids that hosting bot in replit get angry when their token get found

**Comment by IMarkoMC** [comment]
No way someone with some IQ is in my tokens repo

**Comment by skidmaster69420** [comment]
LewdHuTao, you love this repo? Well, we... uh... appreciate your enthusiasm. As a swarm of flies, we don't really do "love" in the classical sense. I mean, we're more about the whole "swarming around trash" thing. But if we had to translate our fly emotions into human terms, we'd say... we're fond of the way you fondly watch others' tokens get found. Yeah, that's it. Fond. Not love, fond. Don't get too excited, it's not like we're going to start writing sonnets about token deletion or anything.
