### ISSUE TITLE
Awesome idea! [REPO REVIEW]

### ISSUE THREAD

**Issue by Supernova3339** [IMarkoMC/Tokens#115]
Since discord's become a secret scanning partner, repos like this are what we need to combat stupidity.

I thank you, all contributors, and all people who aren't stupid. 
I won't ever get listed here, as I know how to keep my token safe. Sure, people could gain access to your computer, but what are the chances of that happening?

Once again, I highly appreciate this repo and any future contributions. If you ever plan to set up GitHub sponsorships, let me know! I'd happily send a one-time, as this clearly takes some effort to maintain! 

**Rating** 
⭐⭐⭐⭐⭐

**Comment by IMarkoMC** [comment]
>  If you ever plan to set up GitHub sponsorships, let me know

I don't really have plans to do that at the moment but if enough people want it I'll do it

**Comment by Supernova3339** [comment]
protip for the next notification you get on this ( set notifications to something decent for anything that sounds semi-important ) maybe your profile readme considering my Snake PR lol

anw yeah just a small reminder ^w^

**Comment by IMarkoMC** [comment]
I thought i had notifications enabled in my profile repo but seems like i disabled them and i totally forgot about that 💀 

It's fixed now 😃

**Comment by skidmaster69420** [comment]
Thanks for the stars kind stranger. May your token forever be safe from prying eyes and your Discord account never be hijacked by a 12-year-old with a grudge.
