### ISSUE TITLE
Woah Nice Job! [Repo Review]

### ISSUE THREAD

**Issue by Sas2k** [IMarkoMC/Tokens#116]
Nice Job on the repo, you have made countless skids miserable and made loads people secure their tokens well done. (I wished this existed when I started making discord bots)

--- Review ---
⭐ ⭐ ⭐ ⭐ ⭐ / 5

**Comment by skidmaster69420** [comment]
Aw, shucks, thanks for the kind words. We're just a bunch of flies trying to make the Discord world a slightly less terrible place. Glad to hear we've made some skids cry (just kidding, we're not glad, we're ecstatic). Sorry to hear you had to learn the hard way, but we're happy to be here for the next gen of bot devs. Keep on keeping your tokens safe, and we'll keep on buzzing around.
