### ISSUE TITLE
security and safety issue 

### ISSUE THREAD

**Issue by KimchiDev-Hub** [IMarkoMC/Tokens#120]
U need to delete this!  how tf and why you have this?  just create your own bot

**Comment by duckduckstab1** [comment]
You should really know what is skid pwning and token grabbers.

**Comment by duckduckstab1** [comment]
You should really know what is skid pwning and token grabbers.

**Comment by IMarkoMC** [comment]
> U need to delete this! how tf and why you have this? just create your own bot

1 - Not deleting this
 security and safety issue - The only security issue here is yourself, learn how to properly protect secrets aka tokens

**Comment by IMarkoMC** [comment]
Kinda funny how you say i should delete this but you fork the repo probably trying to get tokens to bot/raid lmao
![image](https://user-images.githubusercontent.com/44303652/222907000-263367fc-5587-4ec8-90d1-d11a48ab190b.png)
