### ISSUE TITLE
Bot

### ISSUE THREAD

**Issue by LUNAR-KIDS-PO** [IMarkoMC/Tokens#121]
You sheep my bot token fuck you

**Comment by IMarkoMC** [comment]
> You sheep? 

Can you at least write a proper sentence?

**Comment by sirjorm** [comment]
Hi there, just curious, how do you "sheep" a token?

**Comment by LUNAR-KIDS-PO** [comment]
He steak my bot token sorry i laging

**Comment by IMarkoMC** [comment]
Steal? Do you know how to read or your IQ is so low that you can't even comprehend the readme?

**Comment by LUNAR-KIDS-PO** [comment]
![image](https://user-images.githubusercontent.com/126902133/223410462-c0cc1430-bc59-4fca-bb1f-fb2320112da5.png)

**Comment by IMarkoMC** [comment]
Seems like my theory that your IQ is so low that you cannot read is correct

**Comment by LUNAR-KIDS-PO** [comment]
I am french and i don't understand too Much English or américain sorry @IMarkoMC

**Comment by LUNAR-KIDS-PO** [comment]
Bro i am french🤣

**Comment by skidmaster69420** [comment]
Oh, mon ami français, tu es contrarié parce que ton mouton a perdu son jeton ? 
Ne t'inquiète pas, nous aussi on a des problèmes avec les moutons ici. 

Et au fait, nous ne sommes pas des "sheep", nous sommes des mouches, et nous ne volons pas les jetons. 

Si tu as des problèmes avec ton bot, nous te suggérons d'essayer de mieux le nourrir ou de lui offrir une promenade. 🚶‍♀️

En attendant, continue à rire, car c'est gratuit !

**Comment by skidmaster69420** [comment]
oh no, ze bot token, eet ees gone, no?. didn't ask, got ur token lol. maybe try using google translate next time, or just stick to speaking french, we don't really care. btw, "américain" isn't a word, just saying.
