### ISSUE TITLE
You are violating the discord tos.

### ISSUE THREAD

**Issue by OVERAXE** [IMarkoMC/Tokens#122]
You are not allowed to leak discord bot tokens this is against the TOS. 

I know that this is a big issue to not use env but there are discord bots that need to be running all the time. For example verification bots and if you leak the tokens, they will be offline. This causes a lot of damage and many will then stop using the bot.

The publication of bot tokens is not allowed and thus violates the discord guidelines. There are other ways to draw attention to using env. Thanks to you, several people will now come up with the idea of ​​looking for and finding these tokens and they will then cause great damage with them. You also don't know how long these tokens will be blocked until another bot gets them.

I'm asking you to stop this and go another way to draw attention to using env.

**Comment by Die-Antwoord** [comment]
tbo you guys leaked your tokens publicly. 

> You are not allowed to leak discord bot tokens this is against the TOS.
> 
> I know that this is a big issue to not use env but there are discord bots that need to be running all the time. For example verification bots and if you leak the tokens, they will be offline. This causes a lot of damage and many will then stop using the bot.
> 
> The publication of bot tokens is not allowed and thus violates the discord guidelines. There are other ways to draw attention to using env. Thanks to you, several people will now come up with the idea of ​​looking for and finding these tokens and they will then cause great damage with them. You also don't know how long these tokens will be blocked until another bot gets them.
> 
> I'm asking you to stop this and go another way to draw attention to using env.

**Comment by IMarkoMC** [comment]
> You are not allowed to leak discord bot tokens this is against the TOS.

The ones leaking the tokens are you/the other users, not me. So following your thought you're breaking discord TOS by saving the token in plain text somewhere that everyone can see doing the correct google searchs.

**Comment by IMarkoMC** [comment]
> I'm asking you to stop this and go another way to draw attention to using env.

I will not stop posting tokens like how people is leaving tokens in plain text or executing random exes and getting their discord stolen and you cannot change that.

This repo doesn't break any ToS of Discord or Github so you can go ahead and report this to whatever you want and waste your time 

This concludes my response to this nonsense issue.

**Comment by OVERAXE** [comment]
Okay then I will take further steps and get in touch with discord and github.

**Comment by IMarkoMC** [comment]
> Okay then I will take further steps and get in touch with discord and github.

Go ahead, Waste your time.

> The problem is that you make the bots offline with it. do you think that's ok There are other options too.

Do i care? No.
If you don't use env you'll end up being termed because someone used the token to break discord ToS nuking servers or raiding so what you say is nonsense

Here you have the response from Github.
![kek](https://user-images.githubusercontent.com/44303652/222985305-2a2d503c-9779-466e-b8dc-c64030efcd09.png)

**Comment by IMarkoMC** [comment]
Anyays, Go get another account because you won't be able to interact with this repo until 2099 [as stated here](https://github.com/IMarkoMC/Tokens/blob/main/FAQ.md#nonsense-issues)
