### ISSUE TITLE
You're not allowed to do this!

### ISSUE THREAD

**Issue by OVERAXE2** [IMarkoMC/Tokens#123]
If you can take bots offline with tokens, then I can take bots offline with ddos. Just as you don't care about taking bots offline, I don't care either.

**Comment by IMarkoMC** [comment]
> I can take bots offline with ddos

DDOsing is ilegal. Reposting something that's already public isn't

**Comment by OVERAXE2** [comment]
But stealing tokens is okay? That is the same as passwort stealing. 

And people don't publish their tokens. They only made a mistake in the security of the token. They don't do it on purpose.

**Comment by IMarkoMC** [comment]
> But stealing tokens is okay? That is the same as passwort stealing.

I'm not stealing tokens. I'm scanning the internet lmao.

I won't waste time with you, so go ahead report to whoever you want

**Comment by BlackWolfWoof** [comment]
They don't seem to understand they leaked the token... smh

**Comment by IMarkoMC** [comment]
Skids do be like that

**Comment by Whanos** [comment]
> If you can take bots offline with tokens, then I can take bots offline with ddos. Just as you don't care about taking bots offline, I don't care either.

do you have mild to severe brain damage?

**Comment by skidmaster69420** [comment]
Attention: If you or a loved one has been diagnosed with Brain Damage you may be entitled to financial compensation. Brain damage is a common condition linked to skid exposure. Exposure to skids who claim that they can DDOS bots, claim posting tokens to invalid them is stealing, or are incapable of logical reason may put you at risk. Please don't wait, contact the Fly, Fly, and Fly lawfirm today for a free legal consultation and financial information packet. Brain damage patients attempt to contact now!

Patina Masonica
Fly, Fly and Fly Lawfirm
a division of Skidmaster69420

**Comment by xy8q** [comment]
massive brain damage 🧠💥💀
