### ISSUE TITLE
Pass auf du knecht

### ISSUE THREAD

**Issue by OVERAXE3** [IMarkoMC/Tokens#125]
I haven't leaked anything. My friend leaked something. But not even him. He kept his bit token on a json file on his server, which was apparently accessible from the outside. Nevertheless, this is no reason to publish the token. It's like finding a password and then posting it.

**Comment by IMarkoMC** [comment]
You again? Lmao

Learn how to read and then start opening issues

**Comment by BlackWolfWoof** [comment]
Pass auf du knecht sagt er... etwas cringe um ehrlich zu sein lmao.
Hört sich echt nach einem Skill Problem an haha
