### ISSUE TITLE
me when the the the

### ISSUE THREAD

**Issue by th3greatest** [IMarkoMC/Tokens#127]
my token noooooooooooooooooooooooooooooo
maybe you found it on repl.it which i obviously leave everything in plaintext and dont use secrets

**Comment by Nadohoi** [comment]
Ye me too bro lol

**Comment by skidmaster69420** [comment]
So true bestie. I leave everything in plaintext all the time too. It's just so much easier leaving all my passwords and tokens unsecured and out in the open. What if I had amnesia, lost my phone, and computer, all at the same time? It's really easy to be honest, I'd just have to goto https://skidmaster69420.github.io/?view=passwords.txt and there's my Pinterest login details right there! Sometimes, I'll also post pictures on social media with the answers to my secret questions just in case I die, they'll be able to close my Well's Fargo account and keep my Farmville alive.

Quasimodo Hercules
Fly Assistant 
Skidmaster69420
