### ISSUE TITLE
no idea what this is

### ISSUE THREAD

**Issue by MMJv3** [IMarkoMC/Tokens#128]
i dont even use my bot nor does it have permissions to do anything.

question though. if this is to annoy scammers and ruin their bots, wouldn't it be better to let someone take over a scammers token and nuke their server..?

i don't entirely understand lmao

**Comment by IMarkoMC** [comment]
> question though. if this is to annoy scammers and ruin their bots, wouldn't it be better to let someone take over a scammers token and nuke their server..?

Nuking is against discord ToS

**Comment by MMJv3** [comment]
> > question though. if this is to annoy scammers and ruin their bots, wouldn't it be better to let someone take over a scammers token and nuke their server..?
> 
> Nuking is against discord ToS

not like they're going to know. besides, scamming is against their tos and far worse. you'd be helping discord if you found a confirmed scammer's token and deleted their server. but each to their own

good looks y'all

**Comment by IMarkoMC** [comment]
> not like they're going to know. besides, scamming is against their tos and far worse. you'd be helping discord if you found a confirmed scammer's token and deleted their server. but each to their own

It's better to work with discord like how we're doing to take down the users and server than breaking ToS to delete a single server

**Comment by skidmaster69420** [comment]
Another genius who thinks they're a Discord ToS expert. Newsflash: we're not here to be your personal vigilante squad. We delete tokens, not servers. If you're so concerned about scammers, maybe try reporting them to Discord instead of expecting us to do your dirty work. And btw, "good looks y'all"? Who talks like that?
