### ISSUE TITLE
Keep on doing what you do!

### ISSUE THREAD

**Issue by phantomic12** [IMarkoMC/Tokens#129]
Found this repo a couple of days ago like everyone else had, with one of my tokens on here. Naturally I was curious and did some looking, and I wanted to thank you for this. It's very relieving to know that there are people with your skills fighting against scammers and bad actors. Wishing you all the best!

**Comment by skidmaster69420** [comment]
Aww, thanks for the kind words. We're just a bunch of flies trying to make the internet a slightly less terrible place. Glad we could help you sleep better at night knowing your token is gone. Don't worry, we won't let the scammers get you... this time. Keep on keeping on, and try not to get token-jacked again, kay?
