### ISSUE TITLE
Fucked

### ISSUE THREAD

**Issue by MustafaGAmer88** [IMarkoMC/Tokens#130]
U messed my bot now full thread send friend request to !   𝕊𝕡1𝕚𝕥 ~Mustafa<\>#1234
And u mess with wrong clan staff India no 1 raid clan Sp1it with 30k members and 100 of ethical hacker all staffs are hacker now it's time to fucked ur device this is Sp1it link https://discord.gg/sp1itonfire

**Comment by IMarkoMC** [comment]
Lmfao

> send friend request to ! 𝕊𝕡1𝕚𝕥 ~Mustafa<>#1234

i'm not sending a friend request to a random skid in the internet

> And u mess with wrong clan staff India no 1 raid clan Sp1it with 30k members and 100 of ethical hacker all staffs are hacker now it's time to fucked ur device this is Sp1it link https://discord.gg/sp1itonfire

Make me laugh more please.

**Comment by Whanos** [comment]
my dekstop does not have wirus

**Comment by skidmaster69420** [comment]
Hello thank you for contacting skidmaster69420 fly tech support.

You computer has many wirus that will cause computer e-AIDS if they are not removed promptly. You should install a reputable product like SpySheriff or NavaShield. You should also consider buying a [USB condom](https://www.makeuseof.com/what-is-usb-condom/) to help engorge safe internet browsing. If you take these mitigation steps, your computer will be protected from ""ethical hackers"" from "fucked(ing) ur device" using github.com. You can detect these fake hackers by keeping a look out for "leetspeak", such as 1337, r0xx0rz, or sp1it.

Oliver Hiscock
Fly Security Advisor 
Skidmaster69420 LLC
