### ISSUE TITLE
Bro u guys so dumb

### ISSUE THREAD

**Issue by mriknoweverything** [IMarkoMC/Tokens#134]
Discord changed my bot token lol

**Comment by Die-Antwoord** [comment]
> Discord changed my bot token lol

BAHAHAHAHA back at you BRO. . .

**Comment by MineTurtlee** [comment]
skid don't know how to read...

**Comment by skidmaster69420** [comment]
So let's say, for the sake of argument, you said we were so dumb. Say, hypothetically, you were actually the dumb one. Let's say, that would be kind of hypocritical but completed expected for someone who was dumb. It would almost as if the person doesn't understand that we were doing good. That'd be kind of crazy, won't it?

Benito Shipiruden
Fly Columnist
Skidmaster69420
