### ISSUE TITLE
what for?

### ISSUE THREAD

**Issue by Manvvie** [IMarkoMC/Tokens#135]
And why are you actually dumping tokens at all? It’s literally useless, because the discord immediately resets it, you just add work to replace the token in the code, of course it’s cool to try to use someone else’s bot for your own purposes, but alas, this is stopped pretty quickly and in fact - you just put someone else’s bot while it will not notice that the token has been reset.

**Comment by IMarkoMC** [comment]
Maybe if you knew how to read you'll figure out what this repo does.
