### ISSUE TITLE
You guys mind readers or smth?

### ISSUE THREAD

**Issue by GalacticRy** [IMarkoMC/Tokens#137]
I was gonna reset my bot token coz i used it too much on replit but- y'all did it for me anyways... Stay cozy!

**Comment by CatGalaxyUwU** [comment]
Quick question tho. Will you be able to get the token if I don't post it anywhere? (Eg:replit)

**Comment by Niclaslawi** [comment]
I GOT a discord new Messages from discord and Said my token GOT reset

**Comment by GalacticRy** [comment]
> I GOT a discord new Messages from discord and Said my token GOT reset

Dont mind him

**Comment by IMarkoMC** [comment]
> Quick question tho. Will you be able to get the token if I don't post it anywhere? (Eg:replit)


If you leave the token in a plain text file that everyone can read by doing the correct google searches then yes I'll find it and it'll get invalidated again.

You should environment variables to store your tokens, db credentials and stuff

**Comment by GalacticRy** [comment]
> > Quick question tho. Will you be able to get the token if I don't post it anywhere? (Eg:replit)
> 
> If you leave the token in a plain text file that everyone can read by doing the correct google searches then yes I'll find it and it'll get invalidated again.
> 
> You should environment variables to store your tokens, db credentials and stuff

Ohhh thanks

**Comment by IMarkoMC** [comment]
If you're using replit, we have a guide by tobycm, you can see how to use env in replit [here](https://github.com/IMarkoMC/Tokens/blob/main/how_to_use_env/creating_environments_variables/replit.md)

**Comment by skidmaster69420** [comment]
buzz Oh wow, you think we're mind readers? More like, you think you're sneaky, but really you're just predictable. Best of luck protecting your precious bot from yourself, because let's be real, you're the biggest threat to your own security.
