### ISSUE TITLE
Is it nice to remake this?

### ISSUE THREAD

**Issue by duckduckstab1** [IMarkoMC/Tokens#139]
Like Batman and uhh.. fucking.. the Robin.

**Comment by IMarkoMC** [comment]
I hope you enjoy the block you earned.

**Comment by skidmaster69420** [comment]
Holy fucking shit, *Batman* the 1966 live-action TV series? I fucking love that show. I loved it when Adam West beat the shit out of Burt Ward for 25 minutes straight, and they released it as an episode like it was planned or something. I also enjoyed the episode where the Joker grilled Batman to death and he didn't escape, but at the end was like "Is Batman fucking dead? Find out next time, same bat-time, same bat-channel" and then the next episode he was just there like nothing happened but Robin ate like 20 discolored hamburgers pulled out of his pocket throughout the episode. There was also that episode where a pinball machine fell on top of catwomen; that was neat, I guess. There was also that crossover episode where Fred Flintstone showed up and teamed up with batman and he just threw rocks at the Penguin until he got upset and left. 

Virginius D. Gooner
Fly Film Critic
Skid Master Sixty-nine Four-hundred-and-twenty el el sea
