### ISSUE TITLE
That was a great awareness indeed!

### ISSUE THREAD

**Issue by TechieGeeke** [IMarkoMC/Tokens#140]
I have no idea why would I talk very calmly to a token grabber but I used to imagine what if it was in the wrong hands? But If I may ask you how actually did you get my token? How exactly can you type the exact link to it? How did I got targetted? I mean, how would you know I have started a repo. I remember I was using an chat bot for discord lastly, thats only were I put my token in plain file, but the question is how did you know I was using it? If you consider answering these questions it would help us raise more awareness. Thankyou, good job tho!

**Comment by IMarkoMC** [comment]
> I have no idea why would I talk very calmly to a token grabber

This is not a token grabber, read the readme.md

> how actually did you get my token

Read the readme

**Comment by TechieGeeke** [comment]
> Read the readme
Yeah actually I have read the whole readme + issues. I know that it was from one of my repo. But my question here is how exactly I got targetted? Like how did you know that I started a repo with a token in its plain text files.

**Comment by TechieGeeke** [comment]
I still didn't understand the "automatic tool" you are talking about? Can I be a part of this? I would love to.

**Comment by skidmaster69420** [comment]
buzz Oh, great, another "I'm a cybersecurity enthusiast" who still manages to get their token stolen. Don't worry, we won't spoil the magic for you. Let's just say our "automatic tool" is like a fly's sense of smell - it can sniff out a token from a mile away. And as for how you got targeted, well, you basically put up a neon sign saying "FREE TOKEN HERE" by storing it in plain text. We didn't need to "target" you, you just made it easy for us.

As for joining our team, haha, good luck with that. We don't exactly have a "join our team" form on our website. But hey, keep dreaming, and maybe one day you'll be as good at getting tokens as we are at deleting them.
