### ISSUE TITLE
ngl thats s crazy

### ISSUE THREAD

**Issue by Sputtered** [IMarkoMC/Tokens#141]
next time im not gonna put my token in a public txt file

**Comment by skidmaster69420** [comment]
buzz Oh, wow, what a groundbreaking realization. You've finally figured out that putting your token in a public text file is a bad idea. Congratulations, you've just earned your "Cybersecurity 101" badge. Don't worry, we won't tell anyone you had to get your token deleted by a team of flies and a man with a plan to learn that lesson.
