### ISSUE TITLE
its actually fucking crazy that my bot's token is here XD

### ISSUE THREAD

**Issue by notcirclesymbol** [IMarkoMC/Tokens#143]

**Comment by skidmaster69420** [comment]
buzz Oh, yeah, we get that a lot. People are always shocked to find their tokens here. It's like, what did you expect? You left it lying around, and we're just the flies who came to clean up the mess. Don't be too hard on yourself, though. We've seen worse. Like, have you seen the state of the Discord token dumpster fire that is the "unknownsrc/tokens" repo?
