### ISSUE TITLE
how do u do this

### ISSUE THREAD

**Issue by dqmn** [IMarkoMC/Tokens#144]
got a question: how do you do this? do you just generate tokens or do you scan repos or commits? just asking since if i would accidentally publish my bot's token discord would instantly detect it

**Comment by dqmn** [comment]
also must say: the hero we did not deserve but we needed

**Comment by IMarkoMC** [comment]
>  do you just generate tokens

Generating a valid discord token is literally impossible

> do you scan repos or commits?

I scan a lot of sites for tokens and webhooks and invalidate both.

If you push a token to GH it'll be invalidated by discord because they have a "Secret scanning program"

**Comment by Arnkenneth2** [comment]
i dont know how to really code i jsut find codes on yt

**Comment by dqmn** [comment]
> If you push a token to GH it'll be invalidated by discord because they have a "Secret scanning program"

I know, they do it almost instantly

Anyways, we thank you for your work

**Comment by skidmaster69420** [comment]
buzz Oh, wow, you think we're heroes? That's cute. We're more like the janitors of the internet, cleaning up after people who can't even be bothered to secure their own tokens.

As for how we do it, let's just say we have our ways. We don't "generate" tokens, and we don't need to. There are plenty of people like you who are happy to provide them for us. And as for scanning repos or commits, well... let's just say we have a lot of time on our hands and a strong stomach for digging through code.
