### ISSUE TITLE
gj i guess?

### ISSUE THREAD

**Issue by AtillaYasar** [IMarkoMC/Tokens#147]
I have no idea what you're doing but something something "make scammer life miserable". which is good i guess :p

and resetting my bot token is trivial, so no worries.

**Comment by skidmaster69420** [comment]
"Gj i guess?" - we'll take that as a win. And yeah, making scammers' lives miserable is what we do best. Glad you're taking it in stride and resetting your bot token. You're actually one of the more chill ones we've dealt with, so kudos to you.
