### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by musu10gj** [IMarkoMC/Tokens#148]
Hey bro I want to come in Ur team

**Comment by IMarkoMC** [comment]
Hey.

I'm not allowing anyone i don't know to join any of my projects to avoid issues down the road

**Comment by skidmaster69420** [comment]
oh great, another genius who thinks they can just waltz in and join the most elite team of flies in the cybersecurity game. You can't even use grammar let alone the word "ur" correctly. Seriously? We're not running a remedial English class here, bro. If you can't even be bothered to type out "your" in full, how do you expect to keep up with the likes of us? We're deleting Discord tokens not babysitting your grammar lessons.
