### ISSUE TITLE
Thanks bro

### ISSUE THREAD

**Issue by bryton-miller** [IMarkoMC/Tokens#154]
forgot that replit repositories are public lmao

**Comment by skidmaster69420** [comment]
nice recovery, kid. we won't make fun of you (this time). you learned a valuable lesson: replit repos are public, and we're always watching. don't make the same mistake again, or you'll be the main course at our next fly buffet. thanks for being honest, though. you won't find many flies giving out participation trophies, but you get a virtual high-five from us.
