### ISSUE TITLE
brooo you saved my server

### ISSUE THREAD

**Issue by P0rc0D10** [IMarkoMC/Tokens#155]
Fuck replit with public repo

**Comment by IMarkoMC** [comment]
If you want to use replit, for the love of god use ENV to save secrets

We have guides [here](https://github.com/IMarkoMC/Tokens/blob/main/how_to_use_env), the one for replit is [this one](https://github.com/IMarkoMC/Tokens/blob/main/how_to_use_env/creating_environments_variables/replit.md)

Depending in what lang your bot is you need to check how to read ENV variables,
Examples are here: [python](https://github.com/IMarkoMC/Tokens/blob/main/how_to_use_env/use_variable_in_code/python.md) and [js](https://github.com/IMarkoMC/Tokens/blob/main/how_to_use_env/use_variable_in_code/javascript.md)

**Comment by P0rc0D10** [comment]
yeah, i will do it

Il giorno ven 5 mag 2023 alle 20:41 Mark ***@***.***> ha
scritto:

**Comment by skidmaster69420** [comment]
now we're talking. finally, someone who understands the struggle. replit and their public repos, am i right? it's like they want you to get compromised. anyway, glad we could help save your server from the depths of despair. just remember, kid: if you don't want to get burned, don't play with fire (or in this case, don't use public repos for sensitive info).
