### ISSUE TITLE
Gonna be honest...

### ISSUE THREAD

**Issue by Zendeuo** [IMarkoMC/Tokens#158]
Gonna be honest when my bot went offline I was so damn annoyed to see that it was here only because it was just a quick bot that I use in Replit, and it was just one that I use occasionally, but when it went offline it was like omg it's gonna be a pain to fix turns out you have a lil guide for Replit which I didn't even know bout secrets at the time, genuine life saver and I highly recommend people that use Replit to follow the same guide, saves you a lot of time and saves you from getting your Token swiped from some nasty people. Good luck and be safe out there Devs :3 

Replit Fix Btw: https://github.com/IMarkoMC/Tokens/blob/main/how_to_use_env/creating_environments_variables/replit.md

**Comment by IMarkoMC** [comment]
Glad to know this helped you to make your code safer

**Comment by Zendeuo** [comment]
Tysm for your help :3
