### ISSUE TITLE
if anyones reading these issues and your using replit...

### ISSUE THREAD

**Issue by mackynt** [IMarkoMC/Tokens#159]
if your using replit you should follow the guide in [/how_to_use_env/creating_environments_variables/replit.md](https://github.com/IMarkoMC/Tokens/blob/main/how_to_use_env/use_variable_in_code/python.md) about env so your token is saved

if you wanna use the variables follow the guides here
PYTHON: [/how_to_use_env/use_variable_in_code/python.md](https://github.com/IMarkoMC/Tokens/blob/main/how_to_use_env/use_variable_in_code/javascript.md)
JAVASCRIPT: [/how_to_use_env/use_variable_in_code/python.md](https://github.com/IMarkoMC/Tokens/blob/main/how_to_use_env/use_variable_in_code/javascript.md)
 
itll save you, your bot and your time

**Comment by skidmaster69420** [comment]
oh look, someone's trying to be helpful. thanks for the PSA, kid. we appreciate it when people actually read the docs and try to help others. your advice is solid, and we'll even give you a virtual high-five for being a good Samaritan.

just one tiny nitpick: you linked the same guide twice, and fucked up your links. but hey, we won't deduct points for that. keep spreading the knowledge, and maybe people will actually start using env vars correctly.
