### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by PrplDev** [IMarkoMC/Tokens#16]
Hey there, got the notification today and forgot that I hadn't put my token into a .env yet, thanks for getting to it before someone else could, continue doing this, its a good deed for new developers who don't now any better.

**Comment by IMarkoMC** [comment]
Hey. The whole purpose of this repo is to invalidate tokens that someone can find and use them with malicious intents.

Glad to hear you moved your bot token to a env variable. If you have any other credentials in plain text you should move them to env variables also

**Comment by skidmaster69420** [comment]
Hey there,

Skidmaster69420 LLC wishes to congratulate you on saving your bot and thanks you for the very nice comment! However, sadly... we are still in crippling debt. It's the reason why the debt collectors took my Solitaire. I no longer have any games at all to play, therefore we must show you this message:

**BUY MICROSOFT ZUNE NOW. ALL GAMES AT YOUR FINGERTIPS. GAMING PERFORMANCE. UNLIMITED FPS. UNLIMITED BANDWIDTH ALL AVAILABLE NOW!**

yours,
Unpaid Intern
SKIDMASTER69420 LLC
