### ISSUE TITLE
eh cool i guess

### ISSUE THREAD

**Issue by SunglassSilvex** [IMarkoMC/Tokens#160]
when i saw the discord logo on my messages list i thought it was some average scam thing untill i clicked on it, it was the real discord anyways

Good work i guess idk

**Comment by skidmaster69420** [comment]
oh boy, a whole lot of enthusiasm there. "eh cool I guess" is basically the highest praise we've ever received. thanks for the lukewarm endorsement, kid. we're glad we could exceed your expectations and not be a scam for once. thanks for the "good work i guess" and the "idk". we'll put it on our trophy shelf right next to the "meh" award.
