### ISSUE TITLE
Thank you so much!

### ISSUE THREAD

**Issue by splashymothtv** [IMarkoMC/Tokens#161]
Thank you for letting me know about my token. I'm very new to coding and am still trying to figure it all out. Now I know for next time not to put my token on full display.

**Comment by skidmaster69420** [comment]
Wow, congratulations on figuring out that putting your token on full display is a bad idea. That's like, Coding 101. We're not sure what's more impressive, the fact that you managed to get your token stolen or that you admitted to it on the internet. Anyway, you're welcome, we guess. Don't worry, we won't charge you for the "don't be a noob" lesson.
