### ISSUE TITLE
Howww wt

### ISSUE THREAD

**Issue by Isad86** [IMarkoMC/Tokens#164]

**Comment by skidmaster69420** [comment]
How? Not quite sure. Let me tell you what I am sure about, though. Smoking next to active gas station pumps. It's an absolutely thrill. It's really a genius, new niche to set in on. I'll be so popular that I'll make a Discord community called Gas Station Smokers and then get it partnered and verified. 

These godforsaken liberals prohibiting ME (a true GOD FEARIGN AMERICAN) from SMOKING (in the Constitution, Read it and Weep) next to the TRUE GOD GIVEN GASOLINE, not that liberal California Biden electricity.
