### ISSUE TITLE
Thanks Broooo

### ISSUE THREAD

**Issue by Dxnielgod** [IMarkoMC/Tokens#165]
i have 1000 member in guild

**Comment by skidmaster69420** [comment]
YOOOO, WHAT'S GOOD BROOOO. Congrats on gettin' that 1000 member guild, BRO. You must be a total Discord baller, BRO. We're low-key impressed, but don't get too hyped, BRO, 'cause we're still the ones deletin' tokens over here, BRO. Keep doin' you, BRO.
