### ISSUE TITLE
Thank you.

### ISSUE THREAD

**Issue by GraysonMakesGames** [IMarkoMC/Tokens#166]
Thank you for making scammers lives even more miserable.

**Comment by skidmaster69420** [comment]
You're welcome, we guess. We're just doin' the Lord's work, makin' life harder for those scammers and phishers. They're like, the mosquitoes of the internet, and we're the citronella candles. Anyway, don't get too excited, we're not doin' it for the likes or the praise, we're just in it for the sweet, sweet schadenfreude.
