### ISSUE TITLE
I fixed it thanks.

### ISSUE THREAD

**Issue by nonamecoder1** [IMarkoMC/Tokens#170]
@IMarkoMC 
I know u find My bot token in My replit called all in one bots config.json file but i fixed it thank u for finding it.

**Comment by skidmaster69420** [comment]
OH WOW, YOU FIXED IT. Congratulations, you managed to do the bare minimum and not leave your token just chillin' in a public config file. We're not sure what's more impressive, the fact that you left it there in the first place or that you actually bothered to fix it.
