### ISSUE TITLE
Tysm -- :D

### ISSUE THREAD

**Issue by MineTurtlee** [IMarkoMC/Tokens#171]
> EDIT: You shall KEEP UP!! 

Hey! Thanks for posting my **TurtlrBot**'s token here to invalidate it, but I would like to say, next time you don't have to because if it resets again, my music project won't finish. Tysm!! <gud ending but not needed>

Thxx!,
**! MineTurtle2#8381**

**Comment by skidmaster69420** [comment]
Another genius who can't even secure their own token. Thanks for the gratitude, but we're not exactly running a token- invalidation-on-demand service here. If you can't keep your token safe, that's not our problem. Maybe try using a password manager or something. Next time, just don't get your token stolen in the first place, kthxbye.
