### ISSUE TITLE
Why would you reset my token?

### ISSUE THREAD

**Issue by ChocoMilc** [IMarkoMC/Tokens#172]

**Comment by Pabszito** [comment]
Read the README for an answer

**Comment by Kaughts** [comment]
but fr all I was doing was testnig my friends discord bot and my server got spammed, luckily it had literally nothing in it, minor inconvenience

**Comment by Die-Antwoord** [comment]
Read the README for an answer

**Comment by skidmaster69420** [comment]
> but fr all I was doing was testnig my friends discord bot and my server got spammed, luckily it had literally nothing in it, minor inconvenience

oh no, sounds like someone else got their grubby hands on your token and trashed your server. just a coincidence that we deleted it right after, totally unrelated. we're just good samaritans, looking out for your security... and also, btw, "testnig" is not a word

**Comment by kauht** [comment]
> > but fr all I was doing was testnig my friends discord bot and my server got spammed, luckily it had literally nothing in it, minor inconvenience
> 
> oh no, sounds like someone else got their grubby hands on your token and trashed your server. just a coincidence that we deleted it right after, totally unrelated. we're just good samaritans, looking out for your security... and also, btw, "testnig" is not a word

Why are you replying to something a year later? And immature as fuck to point out and obvious typo, just sayin'.
