### ISSUE TITLE
you the best

### ISSUE THREAD

**Issue by Miraii133** [IMarkoMC/Tokens#174]
accidentally leaked my bot token back in 2022, not sure if you guys invalidated it but thanks for your work

also one more issue, i dont see enough angry kids whining about :(

**Comment by IMarkoMC** [comment]
> also one more issue, i don't see enough angry kids whining about :(

They come in waves, if you search in the closed issues there are a lot of really funny angry skids

**Comment by skidmaster69420** [comment]
awww, thanks for the sentiment. as for the angry kids, don't worry, the entitled ones are probably just about to post looking for their participation trophies
