### ISSUE TITLE
Ah! I love you guys! TYSM!

### ISSUE THREAD

**Issue by akjajsjjsaja** [IMarkoMC/Tokens#175]
Very much helped me, in terms of understanding how vunerable my bot token is, and how I can prevent this happening.

ONCE AGAUN THANKSS

**Comment by skidmaster69420** [comment]
awww, group hug. just kidding, we're flies, we don't do hugs. but seriously, don't get too excited, we're not a charity, we're just here to delete tokens and make your life slightly more secure. and btw, it's "vulnerable" and "again", just saying.
