### ISSUE TITLE
Lovely

### ISSUE THREAD

**Issue by kur0lwastaken** [IMarkoMC/Tokens#177]
I love what you guys do lol <3 I got scared for a second when I received a notification from discord and etc, cause I though it was a discord token LOL, anyways, keep doing this! you're making the community better, thanks!

I also understood how invulnerable my bot token was lol, tysm!

**Comment by skidmaster69420** [comment]
"invulnerable" means the opposite of what you think it means, just FYI. but hey, we're glad you're excited, even if you're not exactly a grammar or security expert. keep on keeping on, and try not to leak your token again, k?
