### ISSUE TITLE
stop token grabbing

### ISSUE THREAD

**Issue by OGBlooketCheater** [IMarkoMC/Tokens#180]
plz dude

**Comment by Die-Antwoord** [comment]
> plz dude

start reading . . . 

plz dude

**Comment by IMarkoMC** [comment]
damn, this skid couldn't read a stop sign if it slapped them in the face. Yet somehow they managed to open an issue on your GitHub repo? Must be a miracle... or just plain luck.

**Comment by IMarkoMC** [comment]
Hey there, thanks for opening an issue! Seems like reading might not be your strong suit, but kudos for figuring out how to post on GitHub.
