### ISSUE TITLE
a really nice project!

### ISSUE THREAD

**Issue by gumbobr0t** [IMarkoMC/Tokens#181]

**Comment by gumbobr0t** [comment]
i know so many people using exact tools like this to get bot tokens and account tokens just to do shit with them, you're a hero!

**Comment by IMarkoMC** [comment]
I started doing this due to the amount of people leaking their discord token by accident because of some "verification bot" and then they used their CC to buy nitro and send that nitro to the scammer

**Comment by gumbobr0t** [comment]
yeah that's also a good reason, this project helps so many people

**Comment by Pabszito** [comment]
![image](https://github.com/IMarkoMC/Tokens/assets/37744843/6fe0d10c-4d01-4c7e-baa2-a1ea4118f1a8)

![my honest reaction](https://cdn.discordapp.com/emojis/1116124672703070328.png?size=1024)

**Comment by gumbobr0t** [comment]
> ![image](https://github.com/IMarkoMC/Tokens/assets/37744843/6fe0d10c-4d01-4c7e-baa2-a1ea4118f1a8)
> 
> ![my honest reaction](https://cdn.discordapp.com/emojis/1116124672703070328.png?size=1024)

if you took a sec to read it you would've noticed that i and pierro compeltely rewrote w4sp stealer just becaue we are interested in this & like to learn more about that. i just uploaded hazard because its no longer available on github & people wanted it, so also dont call me skid & not me is the issue that people use our programs for bad purposes

**Comment by gumbobr0t** [comment]
and i own the organisation damagingrose idiot

**Comment by IMarkoMC** [comment]
Totally missed the point but oh well.
