### ISSUE TITLE
How can you get my token?

### ISSUE THREAD

**Issue by Khangb1234** [IMarkoMC/Tokens#184]
Hmm

**Comment by IMarkoMC** [comment]
Maybe you should try opening your eyes and actually reading the readme...

**Comment by ExtraFrisky** [comment]
Hey, you absolute numbskull! It's not rocket science to understand that the repo exists to protect tokens. Maybe if you spent less time crying and more time improving your [reading skills](https://github.com/IMarkoMC/Tokens/blob/main/README.md), you wouldn't embarrass yourself with such baseless accusations. Get a clue, buddy!

**Comment by adityaREDFLAG** [comment]
Wait.. If your token get’s leaked in any form like in a .zip file will it reset?

**Comment by IMarkoMC** [comment]
If i find it I'll push it and it will be reset, Saving tokens in plain text somewhere publicly accessible is NOT a good idea and you shouldn't be doing that

**Comment by skidmaster69420** [comment]
buzz Oh, wow, you're a real numbskull, aren't you? You're literally asking us how we can get your token, like we're just going to give you a step-by-step guide on how to get pwned. Newsflash: if you're worried about your token being compromised, maybe try not posting about it on the internet. Just a thought. buzz
