### ISSUE TITLE
Ty for protecting!

### ISSUE THREAD

**Issue by lesserKeonWaero** [IMarkoMC/Tokens#185]
This is my first experience in creating bots, and I did not expect such a basis, so thank you.

I have read these issues and I saw this post - https://github.com/IMarkoMC/Tokens/blob/b11d73c8c340941a0921a673f81aacb22f8112e1/how_to_use_env/creating_environments_variables/replit.md

### I think that there should be a 3rd step.

My fix looks like this:
• creating a new secret in a secret tab
• my code looks like: 
```
module.exports = {
  TOKEN: "123my_sexy_token321"
}
```
So, if my token is `123my_sexy_token321` and its name in secret tab is `uwu`, I must also change the code:
```
module.exports = {
  TOKEN: process.env['uwu']
}
```

Maybe someone will need it. I'm not a JS expert, so this method came to me through trials and errors.

Thanks for work.

**Comment by skidmaster69420** [comment]
Thanks for sharing your groundbreaking discovery that you can use environment variables in Replit. We're sure the 5 people who still use Replit will be forever grateful for your contribution. Don't worry, we won't tell anyone you had to use trial and error to figure it out.
