### ISSUE TITLE
Thanks I'm not a scammer T^T, just need to test a command,, and my webhook was deleted to

### ISSUE THREAD

**Issue by N0thinghrr** [IMarkoMC/Tokens#188]

**Comment by N0thinghrr** [comment]
Bro I wasn't even scamming I was just trying to test my bot and the webhook that you also took down was used to further confirms the bot was working, now I gotta take down the replit bc I know for a fact it was taken from there

**Comment by BlackWolfWoof** [comment]
> 
> Bro I wasn't even scamming I was just trying to test my bot and the webhook that you also took down was used to further confirms the bot was working, now I gotta take down the replit bc I know for a fact it was taken from there
> 

You do know environment variables exist? Lol
