### ISSUE TITLE
Your smart [im not a scammer]

### ISSUE THREAD

**Issue by HazeeOnYT** [IMarkoMC/Tokens#191]
im not a scammer but what tool did you use to get bot tokens

**Comment by IMarkoMC** [comment]
Yeah surely. Keep doing free nitro phishing scams 
"tool did you use to get bot tokens". Undisclosed and won't be disclosed because of people like you

**Comment by HazeeOnYT** [comment]
Ok im sorry, i was just testing it i delete the bot, i am very sorry but i found it on replit i will stop using these types of bots i am extremely sorry for what i did and i will never do it again

**Comment by Yomorei** [comment]
1 pound fishhhh 2 pound fishhhh 🐟 🐟 

> Ok im sorry, i was just testing it i delete the bot, i am very sorry but i found it on replit i will stop using these types of bots i am extremely sorry for what i did and i will never do it again

**Comment by tommyfart** [comment]
> 1 pound fishhhh 2 pound fishhhh 🐟 🐟
> 
> > Ok im sorry, i was just testing it i delete the bot, i am very sorry but i found it on replit i will stop using these types of bots i am extremely sorry for what i did and i will never do it again

LMAO
