### ISSUE TITLE
You got it but discord protected it

### ISSUE THREAD

**Issue by kobots1** [IMarkoMC/Tokens#192]
![Screenshot_20240609_065154_Gmail](https://github.com/IMarkoMC/Tokens/assets/167325018/2afc1e4b-61d2-43d1-a051-374cbca93576)
![Screenshot_20240609_065150_Gmail](https://github.com/IMarkoMC/Tokens/assets/167325018/2b158d3c-2f05-49bb-b422-8b585ff1e087)
![Screenshot_20240609_063635_Discord](https://github.com/IMarkoMC/Tokens/assets/167325018/9861eba2-1b61-47b0-bdfa-2b6cbeb26a7e)

**Comment by IMarkoMC** [comment]
You missed the entire point of the repository. 
Read the readme before creating a issue.

**Comment by BeanzOnT0ast** [comment]
the bot name.. this dude is a n*zi

**Comment by BeanzOnT0ast** [comment]
@IMarkoMC

**Comment by IMarkoMC** [comment]
> the bot name.. this dude is a n*zi

Yeah and? Discord won't do anything even if you report it with that so idk why you're pinging me.
Anyways there's nothing to do here. Closing
