### ISSUE TITLE
hey why was my testing thing deleted i literally needed to program it for a assignment on an online class

### ISSUE THREAD

**Issue by koikoifishe** [IMarkoMC/Tokens#198]
i was a doing an online basic cyber security class and the assignment to understand how basic rats work was to make a discord webhook "rat" not for distribution and to research it on your own i still had not finished it i need it too complete the class to prove it works thxxxx also it was only on my device
![image](https://github.com/IMarkoMC/Tokens/assets/147331957/fa8029a7-3e9a-486c-a86d-7bacd70fb681)

**Comment by IMarkoMC** [comment]
Yeah sure

**Comment by koikoifishe** [comment]
i legit need it to pass a basic cybersecurity class to understand how rats work and how easy it is to make one and then after i finish it i need to find a way to protect against it on a vm

**Comment by koikoifishe** [comment]
also it was only used on one computer my own computer sadly you cant tell i will send you screenshots clubpenguinoffical is my discord

**Comment by IMarkoMC** [comment]
Surely skid. 
Cry harder
