### ISSUE TITLE
every discord scam bot i found

### ISSUE THREAD

**Issue by HazeeOnYT** [IMarkoMC/Tokens#199]
BoostBot#8233 ID: 1253915812499030047 - fake boost scam

i will be updating if i find more :)

**Comment by Die-Antwoord** [comment]
No point in reporting it here . Please report it to Discord Trust & Safety .

**Comment by skidmaster69420** [comment]
Buzz buzz, thanks for the noise, but we're not the Discord police. Report it to Trust & Safety, they're the ones who get paid to care. We're just a swarm of flies, buzzing around, making skids cry.
