### ISSUE TITLE
ur fatherless

### ISSUE THREAD

**Issue by Beggingmylife** [IMarkoMC/Tokens#21]
Stole my token, reporting

**Comment by User9684** [comment]
Seethe

**Comment by IMarkoMC** [comment]
> Stole my token, reporting

Read the readme of this repo.

**Comment by Pabszito** [comment]
reporting to what? the fbi?

**Comment by skidmaster69420** [comment]
Hello there,

Thank you for reporting us. You are right, I don't have a father. Both my Father nor my Mother showed up at my birth. I was left alone on a fleeting Sunday night being born without both of them. The doctors looked at me disappointed, unsure who to send the medical bill to. It seems that it was all which they were concerned with. Coming up with numerous charges to bill for. Yet having no one to send the bill to. They decided to charge me with my birth. My birthday is a constant reminder of the humongous debt that I face. I fear each second knowing that debt collectors could take my Solitare away to settle a percent of the debt I collected by being born.

At least BOSS is helping pay off the debt, by paying me 0.0000001 cent per year. Which I find very generous. 

Yours,
Unpaid (indebted) Intern
SKIDMASTER 69420 LLC.
