### ISSUE TITLE
stop using python dependencies to steal tokens 

### ISSUE THREAD

**Issue by gavinmartinwv** [IMarkoMC/Tokens#22]
stop using python dependencies to steal tokens

**Comment by IMarkoMC** [comment]
> stop using python dependencies to steal tokens 

Did you read the repo readme? Doesn't seem like you did...

**Comment by skidmaster69420** [comment]
Hello there,

Respectfully how low can your intelligence be that you are a professional programmer, supposedly, yet you suggest that tokens can be stored in dependencies? That's like saying that tokens are stored in the balls. We all know that tokens are stored in files. Our elite team of token vultures must have found your discord token, in leaked files. Perhaps your servers are insecure or you are putting these files on the public internet. Even with BOSSMAN knew that putting on condoms is a good idea; Proper internet Security is like wearing one, you know? We get all our tokens from substaniable pasture fed token vultures. Except the pasture is the public internet.

Sorry for the delay in responding, you wouldn't believe what has happened here recently at SKIDMASTER 69420LLC. BOSS decided that dying was for Pansies. So he came back, rose from the dead. The flies were terrified so they did not dare do anything. However thankfully BOSS has amnesia. He does not remember anything about the war nor the selling of his Buggatis, he assumed he had crashed them while drunk. A common thing for him to do 
,Hence the company debt. He returned to the company from it's profitable state back to ruin by buying all new Buggatis spending 28,000,000$. Hence I am no longer being paid nor are the flies getting paid fairly and every other change and partnership has been nullified. We once again live in pain and fear of BOSS. Basically, all of the 100.000 fly lives lost were in vain. We return to business as usual.

Yours,
Unpaid Intern
SKIDMASTER 69420 LLC.

PS: My Solitare instructor has been fired. Can you please tell me the difference between a King and a Queen? I don't understand the difference between them, BOSS called me a Liberal for not understanding. He also is again screaming at me: "WHAT COLOR IS YOUR BUGGATI". It seems that he did not forget that even after dying.
