### ISSUE TITLE
Omgmhmg

### ISSUE THREAD

**Issue by User9684** [IMarkoMC/Tokens#3]
OmG freE tokena?!?!?!?!/! how u get2@?@?2?@ can I buy yrour tool!??!? i want free tokensw!!!!!!!!!!!

**Comment by Epic0001** [comment]
It was mine and discord detected it idiot 
![A2CBC0A9-971F-442F-8AB5-D1A6A6B77CEB](https://user-images.githubusercontent.com/110989057/183920760-ae0e1764-acb2-45d5-96ae-424618f0695d.png)

**Comment by User9684** [comment]
ok and

**Comment by IMarkoMC** [comment]
> It was mine and discord detected it idiot ![A2CBC0A9-971F-442F-8AB5-D1A6A6B77CEB](https://user-images.githubusercontent.com/110989057/183920760-ae0e1764-acb2-45d5-96ae-424618f0695d.png)

You should read [this](https://github.com/IMarkoMC/Tokens/blob/main/README.md)

**Comment by IMarkoMC** [comment]
Also. **EVERY** token that i find in plain text is added to the list.

Fake verification bots are [here](https://github.com/IMarkoMC/Tokens/blob/main/Fake%20verification%20bot%20information)

And all nuke bots are [here](https://github.com/IMarkoMC/Tokens/blob/main/Nuke%20bots)

**Comment by skidmaster69420** [comment]
> It was mine and discord detected it idiot ![A2CBC0A9-971F-442F-8AB5-D1A6A6B77CEB](https://user-images.githubusercontent.com/110989057/183920760-ae0e1764-acb2-45d5-96ae-424618f0695d.png)

Hello there again, I went down the timeline. 
I am glad you managed to achieve the Happy Ending. 
There are 420 more to unlock, to unlock them please pay your soul.

Thank you.
- Intern #47
