### ISSUE TITLE
im not mad but my bot was just for nuking a racist 💀 

### ISSUE THREAD

**Issue by xixray** [IMarkoMC/Tokens#30]

**Comment by skidmaster69420** [comment]
Hello there,

Thank you for undertaking such a social justice warrior task. However we want to let you know that in that process, you also violated several laws of the Geneva Convention. It is now rumored that Geneva has actually gotten so upset, that he'll come down from the heavens only to teach you a lesson.

Please prepare for the decent of Geneva, it is estimated to take place 03.03.2027 (DD-MM-YY format). It is estimated that he will give you the lesson within 10 seconds of his decent. He will be moving at 499 mph, as predetermined by Geneva's convention entry 23.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
