### ISSUE TITLE
dumbass

### ISSUE THREAD

**Issue by Vskbi** [IMarkoMC/Tokens#31]
bros so stupid had 1000+ tokens just published into github making discord detect it and change it

**Comment by WebUwU** [comment]
bro you are just a bad skid that want to destroy other pp so fuxk you to!

**Comment by IMarkoMC** [comment]
> bros so stupid had 1000+ tokens just published into github making discord detect it and change it

Cry harder + didn't ask + L + ratio + bozo

**Comment by skidmaster69420** [comment]
Hello there,

Thank you for using such eloquent language, we can't believe that you actually managed to fuse the words "dumb" and "ass" without your brain overloading from excessive activity taking place all at once. It's sort of a monumental discovery within the world of science that your brain managed to produce any activity although it had such a long period of inactivity. I believe the beginning of the inactivity started with the date of your birth. We have of course, documented this miracle. The document is currently in the hands of the Fly Legal Department, Sector: Science. 

Sadly, you have been refused the right to access this document. It's been deemed company secret.

Thank you for providing us such valuable data.

yours,
Unpaid Intern
SKIDMASTER69420 LLC
