### ISSUE TITLE
Thank you so much for this repository.

### ISSUE THREAD

**Issue by Corey-Stowe** [IMarkoMC/Tokens#34]
when my Messaging bot token was leaked, Discord noticed me and linked this repo, and I was think why my token was leaked, and the answer was: I forgot to trun private repl repo, so my why bot token was published in here. Thank you so much if this repo is not valid maybe I don't know my bot token was leaked. So thank you so much and keep working

**Comment by skidmaster69420** [comment]
Hello there,

We are glad that everything ended well. We do hope that you'll take care that this does not happen again. This should not sound like a lecture, but rather friendly advice. We do wish to thank you for thanking us. It does not happen often, Unpaid Intern still gets irritated when he sees people being appreciative. However rest assured that it is highly appreciated. Stay awesome :)

Yours,
Fly Department of Appreciation (Fly #4034532)
SKIDMASTER 69420 LLC
