### ISSUE TITLE
hmm

### ISSUE THREAD

**Issue by phthallo** [IMarkoMC/Tokens#35]
hey dude, i kinda panicked when i saw the discord dm but luckily it was just for a test bot that i was trialling some code on. didn't realise that one of my replits was public ✌️ interesting way of letting ppl know but it really impresses that 'don't do that again' part of it lol

**Comment by IMarkoMC** [comment]
The purpose of this repo is that. Send the message **do not save secrets in plain text**. It's incredible the amount of people leaking tokens in chats or some public hosting not knowing what someone can do with your token.

You have guides made by a user in this repo on how to use [ENV variables](https://github.com/IMarkoMC/Tokens/tree/main/how_to_use_env) to store your token, please do that with all your secrets, not only discord tokens like database passwords

**Comment by skidmaster69420** [comment]
Hello there,

We appreciate the thanks. Stay awesome and safe. Also, BOSS has once again invested in BitCoins. Our company is still facing that immense debt, but oh well. Time to invest in BitCoin I guess. The Fly Department for Finances is pretty upset actually. Oh well, we'll see how it all goes from here, i guess.

Anyhow, stay awesome.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
