### ISSUE TITLE
Gracias

### ISSUE THREAD

**Issue by LuckniteIsBack** [IMarkoMC/Tokens#36]
Gracias bro porque se me olvidó poner el repl en privado y me podrían haber nukeado mi server. Muchas gracias.

**Comment by skidmaster69420** [comment]
Hello there,

Although SKIDMASTER69420 LLC, is a English-Fly speaking company, we took liberty to use the program known as "Google Translate" to try and respond to you. 

"Gracias, mantente increíble. Cuídate." 

We hope that our intent to thank you has gotten across. Here a little tidbit about BOSS while he was in Madrid. He layed his elbows on the table also slurped his food and loudly burped in public. The Spanish police tried to arrest him, however even though they had 20 police officers on standby, all of a sudden Tourner Dans Le Vide played out of nowhere. BOSS gained so much strength, he summoned his Bugatti and took them on a race. He ended up crashing and dying, but as he did before. He returned after calling God his bitch. 

Yours
Unpaid Intern
SKIDMASTER69420 LLC
