### ISSUE TITLE
Wtf you leaked my bot token?

### ISSUE THREAD

**Issue by MantisXZ** [IMarkoMC/Tokens#39]
I left a bot running and hosted on a website. i deleted my old acc so i cant change the bot token, thought you have gotten some bad people, youve also gotten some normal bot creators, i left that bot running on a game development server i passed ownership to my friend for.

**Comment by IMarkoMC** [comment]
> Wtf you leaked my bot token? 

If you had more than 0 IQ you would be able to figure out everything

**Comment by skidmaster69420** [comment]
Hello there,

this seems to be the start of your lovely Journey of opening tokens. Of course, this is the first post that had upset BOSS. He usually tends to get upset at all issues, aside from a few. However, with you he got so annoyed. He took away my Solitaire as punishment for me as I mentioned before. In any case, now I have no more games to play. 

You could have prevented this. You could have just read the "READ ME" and wouldn't have had to open so many tickets. That in turn would have meant that I get to keep my Solitaire. But no, no, no. You couldn't just read it. You had to open multiple tickets.

Which caused BOSS to get very upset, and first it was the usual where he threw a cup of HOT coffee at me. However then he saw how many issues you opened and got upset as you saw in #42. You. YOU. **YOU TOOK AWAY MY SOLITAIRE.** 

BUT. MARK MY WORDS. I will get my Solitaire back. In the meanwhile, I hope you stub your toe repeatedly.

Not yours,
Unpaid Intern 
SKIDMASTER69420 LLC.
