### ISSUE TITLE
Idiot 

### ISSUE THREAD

**Issue by Epic0001** [IMarkoMC/Tokens#4]
![F0F72F11-1293-4E51-8E6F-71FB4EEF2706](https://user-images.githubusercontent.com/110989057/183920575-2e253e10-d783-4303-9fba-8cf9c91f5c44.png)
Discord stopped it before any body did anything lol

**Comment by IMarkoMC** [comment]
Cry harder

**Comment by skidmaster69420** [comment]
Hello there,

We do concur with IMarkoMC's remarks here. However we are asking you to put all your tears in a Jar and send it to the boss's address, afterwards you'll be paid 2 dollars... just don't ask any questions and you are good. Curiosity killed the cat. The boss is expecting those tears soon.

Yours
Unpaid Intern
Skidmaster69420 LLC
