### ISSUE TITLE
Sorry  about that.

### ISSUE THREAD

**Issue by MantisXZ** [IMarkoMC/Tokens#40]
Yeah, that was my bad leaving my bot token unprotected, if there's anyway i can support this or maybe help in anyway just dm me on my discord Terminal#0579 or just leave a comment.

I do appreciate what you are doing though.

**Comment by skidmaster69420** [comment]
Hello there,

We are getting a bit alarmed by how many issues you have opened. Please do keep it a minimum, BOSS tends to get upset easily. He has already thrown 2 cups of HOT coffee, compared to the usual 1 cup per day, this is getting alarming. So please help me and yourself by keeping the issues opened small.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
