### ISSUE TITLE
chill

### ISSUE THREAD

**Issue by MantisXZ** [IMarkoMC/Tokens#42]
ight bro, i dont wanna make an env everytime i wanna test a bot, can you please chill a bit, im not pissed i just dont wanna make an env to test a small feature. its annoying to have to reset my token

**Comment by IMarkoMC** [comment]
No.

**Comment by User9684** [comment]
No

**Comment by skidmaster69420** [comment]
Hello there, 

It is unfortunate that you don't wish to Environment Tables every time. However it seems you share that sentiment with your Parents who also didn't adhere to a certain practice while interacting with each other in a certain way. Both are meant for staying safe, be it keeping your token secure or some organ. 

However we do not wish to judge your habits, as it seems to have been genetically passed onto you. We do pity you in that regard. We wish you all the best.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
