### ISSUE TITLE
So your website is a scam to get tokens

### ISSUE THREAD

**Issue by MaxicsSoft** [IMarkoMC/Tokens#45]
Yeah so you are publishing tokens of ppl

**Comment by IMarkoMC** [comment]
Read the readme.

**Comment by MaxicsSoft** [comment]
Ew and where you get em? Isn’t that the website that pretends to help you to get a certain badge?

**Comment by IMarkoMC** [comment]
> Ew and where you get em? Isn’t that the website that pretends to help you to get a certain badge?

I get them from source files that are publicly available in multiple sites and some from chats. Then as the readme says, i post them to make them invalid to avoid others searching for free tokens for malicious intent to use them

**Comment by MaxicsSoft** [comment]
Ok so the source prob https://discordactivedev.vercel.app/

**Comment by MaxicsSoft** [comment]
I didn’t understand at the start

**Comment by IMarkoMC** [comment]
> Ok so the source prob https://discordactivedev.vercel.app/

No. That's not the source, I'm getting them from publicly accessible files. 
If you think that page is leaking tokens contact the owner and make him check the security of the page

**Comment by MaxicsSoft** [comment]
Ok
