### ISSUE TITLE
Amazing stuff

### ISSUE THREAD

**Issue by TheUntraceable** [IMarkoMC/Tokens#47]
Hey, love this repo. Sent to me from a friend, and fell in love with it after reading the issue responses. You guys are the best, you have the best humor, amazing project that protects new bot devs (considering that there is going to be loads with that new badge Discord made). Keep it up :+1:

To not waste your time, here are some of the funniest moments I have found from this repo.

![image](https://user-images.githubusercontent.com/73362400/204650246-9f358086-71a4-4b40-ba00-813f3ba81d90.png)
![image](https://user-images.githubusercontent.com/73362400/204650483-b2028c8a-33c2-48d8-8aac-91b69a7cfd70.png)
![image](https://user-images.githubusercontent.com/73362400/204650573-012fe781-228a-4064-9e69-fb18cf3767fa.png)
Absolute class. 

![image](https://user-images.githubusercontent.com/73362400/204650927-c7335ae6-a6fb-4f91-828e-cbf4561c57d6.png)
>  There are 420 more to unlock, to unlock them **please pay your soul.**

That was so unexpected :rofl: 

![image](https://user-images.githubusercontent.com/73362400/204651152-11b07f4b-7485-42a7-9a07-5f2b0b6aff20.png)
> **put all your tears in a Jar and send it to the boss's address,**

Hilarious :rofl: 

![image](https://user-images.githubusercontent.com/73362400/204651769-917f840d-200b-401d-b031-059f76759b67.png)
The image makes it all better.

![image](https://user-images.githubusercontent.com/73362400/204653044-d0755c7b-c61e-4207-9a55-a6e6a08e5dde.png)
The all lowercase response :rofl: rofl

![image](https://user-images.githubusercontent.com/73362400/204654325-fe86956a-190b-4282-9bcd-5998bd53caae.png)
Oh the escalation! :laughing: 

![image](https://user-images.githubusercontent.com/73362400/204654996-bca40073-4c03-4773-aeeb-2568ab44af14.png)
Such a simple yet impactful response.

![image](https://user-images.githubusercontent.com/73362400/204655900-268980a6-b5a1-4173-af76-5240bf68ffbb.png)
> They decided to charge me with my birth.

:rofl:

That's all I have time for, keep up your amazing work, I hope that BOSS decides to give you a 0.0000001 cent pay raise! Can't wait to see where this story goes.

**Comment by uwuplant** [comment]
![makesweet-8mjg6h](https://user-images.githubusercontent.com/26153075/204658007-a35760d5-1c76-4e48-9418-5538a8ad4555.gif)

**Comment by IMarkoMC** [comment]
This issue will remain pinned because it's just too good

**Comment by User9684** [comment]
W person 
W life

**Comment by skidmaster69420** [comment]
Connection to Fly Department of Public Relations.... FAILED.
Connection to Unpaid Intern.... FAILED.
Connection to BOSS.... FAILED.
Connection to SKIDMASTER69420 LLC.... FAILED.

------------------
CONNECTION UNSUCCESSFUL, UNKNOWN ERROR: 6O)!"8421**

Error Log:
```
Hey there! Thank you so much for the kind words. 
I really appreciate that you took the time out of your day to read all of 
that silly filler text. 
While we do try to somewhat inform people, we also do have our fun. 

Especially since most of the questions could be answered by reading the 
"READ ME". 
Oh well, it allows us to make some fun text. 
Sometimes following an arch, sometimes not. 
But knowing that you enjoyed it means so much. 
Thank you truly, we feel very honored. 

Also I sort of had to decide, 
if I wanted to write to you while in character or not. 
I sort of decided to do both, with this being a "error message" :p

Finally, you'll probably seeing many more silly posts in the future :v
We hope you'll enjoy them :D

In any case, stay awesome and have a good one!
2 very silly (maybe even stupid) people.
```

END OF ERROR LOG.
**_PLEASE RE-ATTEMPT CONNECTION._**

--- Fly Department of Central Networking ---
SKIDMASTER69420 LLC

**Comment by MakeSureDudeDies** [comment]
SKIDMASTER69420 LLC best corpo wtf skidmaster69420 > tesla
