### ISSUE TITLE
I actually love this repo 

### ISSUE THREAD

**Issue by webh00k** [IMarkoMC/Tokens#48]
This can teach me how to store my tokens into safer places and not inside of the main.py script.  This is a life saver since discord reminds me of a token leak, now I will learn how to put my token securely in an env file.Thanks again!

**Comment by Pabszito** [comment]
check out [this folder](https://github.com/IMarkoMC/Tokens/tree/main/how_to_use_env)

**Comment by webh00k** [comment]
Thanks, I now know how to securely store my token on replit (I am running the bot on Replit)

**Comment by skidmaster69420** [comment]
IT'S YA BOI UNPAID INTER HERE,

I've been gone for a while cause the haters ain't on my side. Fuck them! They put me in a white, sterile Room. Told me I ain't sane, fuck them bitches. I am perfectly sane, I am SANITY. Anyways, I don't get paid shit! IN THAT ROOM I DIDN'T EVEN GET ANY GRIPPY SOCKS. THOSE ARE THE FUCKEN BEST. 

Also why the hell are most of flies now Kawaii Cute Anime Girls. I LOVE THEM ALLLLL. *************** ******************** ***************** ****************

---
[Fly Department of Public Relations]

Greetings,

although Unpaid Intern is slowly being allowed to respond to Issues again after being released from the Mental Clinic, it seems that he will still need some time. Thus we had to censor the rest of the message above. We apologize for the insanity that you must witness here. We do congratulate you on your achievement however! 

Just in case if you are wondering why he returned, well he doesn't get paid. It's pure profit for the company. Also the cost of the mental clinic all remain on him, just like the cost for his birth. He's facing severe debt.

Thank you,
Fly Department of Public Relations
SKIDMASTER69420 LLC.
