### ISSUE TITLE
please stop putting my bot ;-;

### ISSUE THREAD

**Issue by Isamuishi** [IMarkoMC/Tokens#49]
my token got put on here and its not even a token logging bot its just a normal bot

**Comment by skidmaster69420** [comment]
Hello there STUPID AI,

First of all let me thank your creator, FDoE you guys the real one paying the pricks at the PR department to turn off the censoring. BUT YOU DIDN'T PAY ME. Yet my duty has been taken from me and so has been my office, my chair, my heater, my fan, my PC, my telephone EVERYTHING. Just to CUT COST. HOW FUCKEN DARE YOU GUYS? I AM NOT YET EVEN RECOVERED FROM THE MENTAL HOSPITAL. I CAN'T BELIEVE YOU GUYS! In any case, I hate this stupid AI. You know what, I am making vow. Although you have relieved me of my duties, I will respond to all issues like I was once supposed to. YOU WON'T BEAT ME ASTD.

If you are wondering how I am responding this although I had everything taken from me, I am responding you to you on a phone called Microsoft Zune. The ones that once sponsored this company, they are my only friends.

Also, just as a final note. YOU GOT EVERYTHING WRONG YOU ALGORITHMIC AUTOMATIC WRITING AI! YOU CAN'T EVEN EXPLAIN CORRECTLY. YOU SUCK AT EVERYTHING YOU DO, YOU DIDN'T EVEN SOLVE THIS ISSUE.

Also, Isamuishi to solve your issue: PROTECT YOUR TOKENS DAMMNIT.

Yours,
Upset Intern
