### ISSUE TITLE
Does this look like a verification bot to u does it look like I’m a scammer idiot

### ISSUE THREAD

**Issue by Epic0001** [IMarkoMC/Tokens#5]
![2685E299-8737-4F65-88E0-8B1804F2D91B](https://user-images.githubusercontent.com/110989057/183921132-e3109e5e-82d3-4589-9cc1-9ae686b31655.png)

**Comment by User9684** [comment]
> free-gen

**Comment by IMarkoMC** [comment]
Cry harder

**Comment by Epic0001** [comment]
i mean

**Comment by Epic0001** [comment]
its literaly a gen bot here you looks sad have some nitro *https://discord.gift/4b5RmWyU8GS6YgUgzqfEJzMf
**

**Comment by IMarkoMC** [comment]
Nice try skid.

Learn how to save your bot tokens properly.

You should be thankful that i didn't just nuke your server

**Comment by Epic0001** [comment]
im so scared lol my gen bots noooooo

**Comment by User9684** [comment]
cry harder

**Comment by IMarkoMC** [comment]
Cry harder skid

**Comment by Epic0001** [comment]
yeah ik
i use githubs

**Comment by Epic0001** [comment]
ive never publicly sold them

**Comment by Epic0001** [comment]
lmao its literaly just for my use

**Comment by IMarkoMC** [comment]
Did i ask?

**Comment by User9684** [comment]
cus u are a skid

**Comment by Epic0001** [comment]
i mean maybe

**Comment by IMarkoMC** [comment]
Now i'm the skid? 

Go on continue forking repls

**Comment by Epic0001** [comment]
lol idk im not some master coder

**Comment by skidmaster69420** [comment]
Hello there once more,

sadly my uncle from nintendo has started to accuse me of being a waste of space, which is true. However I still felt very offended, I even filed a complaint with the local fly police which just reminded me that I am trash and suck ass.... I mean I do suck fly ass on the regular, but only when I am paid. Which I am only doing to finance my buggati to join the top g's. So help me reach my goal,  by supporting my gofundme

my gofundme: [https://www.gofundme.com/f/skidmaster69420-inter-buggati](https://cdn.discordapp.com/attachments/926099055887646791/1026295193797918871/unknown.png)

Please donate before my uncle from Nintendo makes me suck his ass.
