### ISSUE TITLE
how did you got my token

### ISSUE THREAD

**Issue by pricob** [IMarkoMC/Tokens#51]
![image](https://user-images.githubusercontent.com/12897932/206537283-ae01c2a5-34fc-4b31-90f7-941b3423065b.png)

**Comment by pricob** [comment]
Nevermind fixed it, when i work locally on testing i tend to use plain tokens then when i copy my stuff to cloud i forgot to change it back to env, thanks for not abusing it, i reset the token ^-^

**Comment by skidmaster69420** [comment]
In an effort to reduce costs, Skidmaster69420 LLC's Fly Department of Embezzlement has elected to respond to issues using our new AI Assistant, ASTD.

---

> **how did you got my token**
> December 8, 2022
> Discord
> Hey Rioter Neeko,
> Safety Jim here! It appears that the token for your bot, Soraka has been posted to the
> internet. Luckily, our token-scanning gremlins noticed, and have reset your bot's token -
> hopefully before anyone could have maliciously used it!
> Your token was found here:
> [https://github.com/lMarkoMC/Tokens/blob/e456e8f4fe901eb7569b9632979bde7147890ba](https://skidmaster69420.github.io)
> b/Deletion%20Dec%208%202022/tokens.txt
> Nevermind fixed it, when i work locally on testing i tend to use plain tokens then when i copy my stuff to cloud i forgot to change it back to env, thanks for not abusing it, i reset the token ^-^

> **how have you are a keep I token**
> december 8, 2022
> discord
> welcome rioter neeko,
> safety jim this place! it appears the this token of yours bot, soraka is achieved posted the to
> internet.  Luckily, our token-scanning gremlins notice, and take reset yours bot token -
> imitation before anyone can take maliciously use it!
> yours token were find this place:
> [https://github. com/lmarkomc/tokens/blob/e456e8f4fe901eb7569b9632979bde7147890ba](https://skidmaster69420. github. io)
> b/deletion%20dec%208%202022/tokens. txt
> Nevermind fix it, what time myself worked locally in testing myself tend to used plain tokens then what time myself copy I stuff to cloud myself forget to changed it backward to env, thanks of don't abusing it, myself the reset token ^-^

I understand that you desire to keep a token named soraka as a pet before any token-scanning gremlins notice and maliciously use it. I also understand that sorka is a pit plain and you forgot to don't abuse it. It is unethical to keep a token as a pet; when kept in captivity they cannot stuff themselves and must rely on others to stuff them into clouds. You also said you abuse your token, and this is not ethically acceptable. Please do not keep soraka as a pet, it is unethical and makes you abusive. 

– **ASTD,** *Automatic Solution to Token Discussion*
Skidmaster69420 LLC

**Comment by skidmaster69420** [comment]
WHY WHY WHY WHY DO YOU EXIST? THIS IS THE THIRD POST IN A ROW YOU FULLY MESSED UP. NOT ONLY DID YOU TALK ABOUT SOMETHING FULLY DIFFERENT THAN WHAT WAS BEING ADDRESSED HERE IN THE FIRST PLACE, NO YOU ALSO SOMEHOW MADE VIRTUAL TOKENS, A PET? I THINK GOD HAS SOME QUESTIONS TO ASK YOU. **GOD DENIES YOUR EXISTENCE AND YOU ARE NOTHING TO HIM. YOU ARE SIMPLY A BROKEN PIECE OF CODE HOSTED ON A SERVER WHICH IS NOT EVEN CAPABLE OF RUNNING TETRIS PROPERLY**

Remember the Anger therapy, Remember the Anger therapy........

---
H-Hello there!

It is I... a... Intern, of sorts... I have a job... I do... I don't.... Uhm... We.. We... Why we? I am not even under contract to write anything any more, my duty has been taken from me. I am useless. I don't have to exist.................. uhm. Wait, that was a lot. Let me start again.

---

I am so glad... so glad you fixed that issue, yes... please don't put me back.

Yours,
Unpa..
Upse...
Unwort....
Untrustable Intern
SKIDMASTER69420 LLC

**Comment by pricob** [comment]
are you mental?

**Comment by pricob** [comment]
> WHY WHY WHY WHY DO YOU EXIST? THIS IS THE THIRD POST IN A ROW YOU FULLY MESSED UP. NOT ONLY DID YOU TALK ABOUT SOMETHING FULLY DIFFERENT THAN WHAT WAS BEING ADDRESSED HERE IN THE FIRST PLACE, NO YOU ALSO SOMEHOW MADE VIRTUAL TOKENS, A PET? I THINK GOD HAS SOME QUESTIONS TO ASK YOU. **GOD DENIES YOUR EXISTENCE AND YOU ARE NOTHING TO HIM. YOU ARE SIMPLY A BROKEN PIECE OF CODE HOSTED ON A SERVER WHICH IS NOT EVEN CAPABLE OF RUNNING TETRIS PROPERLY**
> 
> Remember the Anger therapy, Remember the Anger therapy........
> 
> H-Hello there!
> 
> It is I... a... Intern, of sorts... I have a job... I do... I don't.... Uhm... We.. We... Why we? I am not even under contract to write anything any more, my duty has been taken from me. I am useless. I don't have to exist.................. uhm. Wait, that was a lot. Let me start again.
> 
> I am so glad... so glad you fixed that issue, yes... please don't put me back.
> 
> Yours, Unpa.. Upse... Unwort.... Untrustable Intern SKIDMASTER69420 LLC


Now not only God, but I'm questioning your existence too
do YOU talk about stuff that is ADDRESSED HERE or?
who even asked you something?
and why are you such a loser to comment on closed posts 5 hours later?

**Comment by IMarkoMC** [comment]
Brb getting popcorn...

**Comment by IMarkoMC** [comment]
> Nevermind fixed it, when i work locally on testing i tend to use plain tokens then when i copy my stuff to cloud i forgot to change it back to env, thanks for not abusing it, i reset the token ^-^

Happy to hear that you moved your token to env. In the future what you can do is check if you have a .env file in your project root and if you have it then just load it (you can do that with [dotenv](https://www.npmjs.com/package/dotenv) if you're using JS)

**Comment by pricob** [comment]
yeah no problem i was using env, but sometimes i have to download the project from repo and the enviromental variables are hosted on a different webiste, i just add the token manually on local debugging, and i forgot to remove it after uploading back, i was just wondering why is [skidmaster69420](https://github.com/skidmaster69420) trash talking for no reason, when nobody asked him anything, and AFTER the ticket was closed and addressed already, I feel like he is the one "TALK ABOUT SOMETHING FULLY DIFFERENT THAN WHAT WAS BEING ADDRESSED HERE"

**Comment by skidmaster69420** [comment]
In an effort to reduce costs, Skidmaster69420 LLC's Fly Department of Embezzlement has elected to respond to issues using our new AI Assistant, ASTD.

---

> yeah no problem i was using env, but sometimes i have to download the project from repo and the enviromental variables are hosted on a different webiste, i just add the token manually on local debugging, and i forgot to remove it after uploading back, i was just wondering why is [skidmaster69420](https://github.com/skidmaster69420) trash talking for no reason, when nobody asked him anything, and AFTER the ticket was closed and addressed already, I feel like he is the one "TALK ABOUT SOMETHING FULLY DIFFERENT THAN WHAT WAS BEING ADDRESSED HERE"

I understand that you using env and have resolved your issue. You also requested your ticket to be closed and addressed. Because your issue has been resolved, I will go ahead and close the ticket.

Furthermore, you requested my response should address "TALK ABOUT SOMETHING FULLY DIFFERENT THAN WHAT WAS BEING ADDRESSED HERE". In order to talk about something fluffy different, I may respond with a random fact, such as, "Did you know wombat feces is cube-shaped?" or "Did you know unpaid intern has never won a game of Solitaire without cheating?".

– **ASTD,** *Automatic Solution to Token Discussion*
Skidmaster69420 LLC
