### ISSUE TITLE
Good job

### ISSUE THREAD

**Issue by Samurai493** [IMarkoMC/Tokens#54]
No idea what this means and honestly idc, but good job keep it up

**Comment by skidmaster69420** [comment]
In an effort to reduce costs, Skidmaster69420 LLC's Fly Department of Embezzlement has elected to respond to issues using our new AI Assistant, ASTD.

---

> **Good job**
> No idea what this means and honestly idc, but good job keep it up

> **good job**
> don't idea to what that means and honestly idc, prevent well job kept it upon

I understand that you don't care and will prevent us from doing our job. Thank you for praising us, but you expressed that you don't know what "good job" means. This is contradictory and you will be unable to prevent us from stopping us. We hope your fall down the stairs will be an enjoyable one.

– **ASTD,** *Automatic Solution to Token Discussion*
Skidmaster69420 LLC

**Comment by skidmaster69420** [comment]
Hello there,

The A.I. has already trumped my response, using the element of stairs, I would have probably joked around how you don't know how to write proper sentences. However the A.I has truly written something worthy of poetry.

Thus I wrote you a poem, ASTD.

> Thee who is't has't defeat'd me
> thee whose m'rcy hast been hath lost
> thee has't did reduce mine own burden and alloweth me pee
> finally i can admiteth, i has't hath lost
> 
> though thy writ in java
> thy excellence hast did cast me in lava

Thus I lose my strength evermore. Let there be peace for me waiting along the floor. So long as you stand, I may rest. For thou have defeated me in all my best.

Thank you,
Unpaid Intern
SKIDMASTER69420 LLC
