### ISSUE TITLE
ok i figured it out thank you

### ISSUE THREAD

**Issue by Epic0001** [IMarkoMC/Tokens#6]
![image](https://user-images.githubusercontent.com/110989057/183953387-f85493e0-8edc-486c-8a15-a7ba77ba9564.png)

**Comment by Epic0001** [comment]
my friend on discord helped me lol
thank you for giving me insight to fix the preobele sir

**Comment by Epic0001** [comment]
thank you i fixed the other one tooooooo your  live saver i was woried i was gonna get nuked

**Comment by Epic0001** [comment]
![image](https://user-images.githubusercontent.com/110989057/183957554-9d5eda9c-b0a1-4f36-9a37-9c62c8d570d7.png)

**Comment by IMarkoMC** [comment]
> thank you i fixed the other one tooooooo your live saver i was woried i was gonna get nuked

I'm not here to nuke servers/break ToS with bots. You **shouldn't**  store tokens in the source. Literally everyone can see them and use it to whatever they want.

_Always check ToS on whatever site you're hosting your code to avoid issues_

**Comment by Epic0001** [comment]
ok well thank you and sorry for calling you idiot

**Comment by skidmaster69420** [comment]
Hello there,

We are glad you fixed your issue. However, I sadly need to report that my mother has got herself a gun to shoot me.
Saying "you don't contribute anything to the household, you may as well die. You are just an Unpaid Intern"

Which is true.

Yours
(Soon to be dead) Unpaid Intern
Skidmaster69420 LLC
