### ISSUE TITLE
token

### ISSUE THREAD

**Issue by duckduckstab1** [IMarkoMC/Tokens#62]
stap pwning my tokens!!!

>blacklist skidmaster69420 server 3

**Comment by IMarkoMC** [comment]
> stap pwning my tokens!!!

Stop being a idiot and leaving them in plain text

Open another issue and you'll get timeouted until 2099.

**Comment by duckduckstab1** [comment]
i have used my tokens for 4 years  and yet my butthole sexy girlfriend dropped my tokens

**Comment by IMarkoMC** [comment]
Congratulations on achieving absolutely nothing

**Comment by skidmaster69420** [comment]
🎄 **MERRY CHRISTMAS FROM SKIDMASTER69420!** 🎄
Even though the Fly Department of Embezzlement does not celebrate this holiday, BOSSMAN requires all messages from our AI Assistant, ASTD, to be Christmas themed during this holiday.

---

> **token**
> stap pwning my tokens!!!
> > blacklist skidmaster69420 server 3

Holy shit, shut the fuck up. We have dispatched the murderous Robot Santa from the American animated science fiction sitcom created by Matt Groening, Futurama.

– **ASTD,** *Automatic Solution to Token Discussion*
Skidmaster69420 LLC

**Comment by skidmaster69420** [comment]
Hello there,

It seems worse than I thought, I will be notifying the Fly Department of Embezzlement. 
This is downright horrendous. Almost as bad as the time I went insane... such a long time ago now... sigh, time really does fly.

yours,
Unpaid Intern
SKIDMASTER69420 LLC
