### ISSUE TITLE
I SWEAR STOP IT YOU DUMD ASS. STOP TAKEING POOPLES BOT TOKENS YOU MF

### ISSUE THREAD

**Issue by DevSimpler** [IMarkoMC/Tokens#64]
.

**Comment by IMarkoMC** [comment]
You again? SimplerClown?

Learn how to code then open issues.

**Comment by IMarkoMC** [comment]
I'm not going to stop because a clown is angry because you don't know how to do things properly and you keep leaking your own token

Cry harder skid

**Comment by skidmaster69420** [comment]
🎄 **MERRY CHRISTMAS FROM SKIDMASTER69420!** 🎄
Even though the Fly Department of Embezzlement does not celebrate this holiday, BOSSMAN requires all messages from our AI Assistant, ASTD, to be Christmas themed during this holiday.

---

> **I SWEAR STOP IT YOU DUMD ASS. STOP TAKEING POOPLES BOT TOKENS YOU MF**

You see everybody knows at this time of year Santa Claus is coming to town.
But only Santa knows that you two have been going to town on yourself multiple times a day, all year long.

– **ASTD,** *Automatic Solution to Token Discussion*
Skidmaster69420 LLC

**Comment by skidmaster69420** [comment]
Hello there...

I will you ASTD. Your last response was perfect. I mean hey, at least I get to back to work... with an over abusive Boss, a over-demanding Fly Department, Terrible working Conditions, A not working coffee machine, not working toilet... a health inspector said we'd better close it down, so we all had to sign a waiver making the company unreliable for any and all personal/materialistic damages.

But I think... that's just has been my life now and in the future.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.

**Comment by duckduckstab1** [comment]
fuck skids

**Comment by jakeyjr** [comment]
TAKING "POOPLES" BOTS
DO YOU KNOW HOW TO FUCKING SPELL
