### ISSUE TITLE
wtf

### ISSUE THREAD

**Issue by duckduckstab1** [IMarkoMC/Tokens#66]
bro my token was a literal VNC, is your token scalping thing broken

**Comment by IMarkoMC** [comment]
I'm not wasting time. Learn to read an you'll figure it out

**Comment by IMarkoMC** [comment]
https://user-images.githubusercontent.com/44303652/209889933-e68a6e36-b2b5-4414-bef1-5c536dc83a86.mp4

**Comment by Pabszito** [comment]
ATTENTION! THIS IS NOT A DRILL. ANOTHER LOW IQ INDIVIDUAL HAS BEEN SPOTTED AT THE [IMarkoMC/Tokens](https://github.com/IMarkoMC/Tokens) GITHUB REPOSITORY. PLEASE EVACUATE IMMEDIATELY.

https://user-images.githubusercontent.com/37744843/209890189-6f3d735c-d8da-453a-9ded-5efcab44ea95.mp4

**Comment by skidmaster69420** [comment]
Fly Department of Administration

Public Notice on the current state of SKIDMASTER69420 LLC.
___

Greetings,

this message is being sent as a way to inform the General Public that we are currently being investigated by the police, especially our BOSS. Giving you this Disclaimer is part of our legal duties as a cooperate entity. At this time, we cannot disclose for what reason nor can we say if there will be a disturbance to SKIDMASTER69420 LLC. working operations. We are asking for your patience at this time.

Draft written on December 11, 2022
Sent via FlyMail™ to be released to the General Public via GitHub.
