### ISSUE TITLE
Bro ur bot or wtf

### ISSUE THREAD

**Issue by MohxKd** [IMarkoMC/Tokens#68]
Lol how do u do that shit do u have a life?

**Comment by IMarkoMC** [comment]
Look at you little skid

**Comment by skidmaster69420** [comment]
Date: 14.12.2022
Hello there,

Oh.

>**Warning**
> 🚨🚨 **SKID ALERT** 🚨🚨 **SKID ALERT** 🚨🚨 **SKID ALERT** 🚨🚨
>
> **SKID DETECTED. PERSON WITH NO LIFE IDENTIFIED. PERSON WHO'S A COMPLETE MORON RECOGNIZED. PERSON WHO HAS ACCOMPLISHED NOTHING IN LIFE HAS BEEN DETECTED. PERSON WHO IS AS ORIGINAL AS A SLICE OF CHEESE DETECTED.**'
>
> 🚨🚨 **SKID ALERT** 🚨🚨 **SKID ALERT** 🚨🚨 **SKID ALERT** 🚨🚨

Sorry, I accidentally purposefully pressed the Skid alert button that BOSS is working on to fully replace me, I do feel insulted but it's pretty cool.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
