### ISSUE TITLE
it well help a lot if you guys read this and make a reply 

### ISSUE THREAD

**Issue by holdulv1** [IMarkoMC/Tokens#70]
** what tools is the multiple tools and what automated scanning processes across the internet do you guys use. thanks for publish the tokens but can you tell me what tools and what automated scanning processes across the internet you guys use
pls tell me so i can and you can make the internet more safe from anyone**

**Comment by IMarkoMC** [comment]
We're not disclosing what tools we use to avoid the use of such thing to steal tokens and use it in nuke and raid bots.

**Comment by holdulv1** [comment]
ok then. Then let me self research what you guys use

**Comment by holdulv1** [comment]
it can take some time but at the end i will know what to guys use

**Comment by IMarkoMC** [comment]
Good luck

**Comment by holdulv1** [comment]
thanks

**Comment by holdulv1** [comment]
what is your email so i can contact you know without github admins can see it good hackers are best

**Comment by holdulv1** [comment]
i hate black hat hackers

**Comment by holdulv1** [comment]
black hat hackers are so dum

**Comment by holdulv1** [comment]
even fbi are better then the black hat hackers is also why the fbi have only been hacked to or 1 time

**Comment by holdulv1** [comment]
he he

**Comment by holdulv1** [comment]
xd

**Comment by holdulv1** [comment]
i know that. You know that i have used a password that was DSn.com8

**Comment by holdulv1** [comment]
you use some type of maybe discord bots that do so users get there token out of them self

**Comment by holdulv1** [comment]
i konw how some of you got mt data ha ha xd

**Comment by holdulv1** [comment]
but the problem with github is that some one eles can stel all you guys data by just one click

**Comment by holdulv1** [comment]
xd

**Comment by RealJeffBezosNotFake** [comment]
For future complaints, please email `tokens@skids.lol`
And if you can, please send information how to get my hair back please even going to space didn't fix it i'm getting desperate

**Comment by skidmaster69420** [comment]
Date: 16.12.2022 

Hello there,

sadly this post was stuck in a different world line aka the spam inbox. We are getting around to clear the spam inbox, however do be aware that we really aren't even trying to give you a high quality response, we only are doing this to comply with the Court Order that we have received recently forcing us to resume our duties. 

Also what is a subpoena? I think I might just ignore it :)

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
