### ISSUE TITLE
how did you got my token when i use a lock on my token 

### ISSUE THREAD

**Issue by FireFlyButBlue** [IMarkoMC/Tokens#72]
i use the lock mode on replit to keep my token safe so i dont know how you got it

**Comment by FireFlyButBlue** [comment]
@IMarkoMC help

**Comment by IMarkoMC** [comment]
First of all avoid mentioning users in this repo.

Second. You need to use ENV variables to store the tokens no matter where you host your code. You have examples [in this folder ](https://github.com/IMarkoMC/Tokens/tree/main/how_to_use_env)

**Comment by FireFlyButBlue** [comment]
i already did that

**Comment by FireFlyButBlue** [comment]
i use client.run(process.env.TOKEN) 
in all the places where i host my tokens

**Comment by IMarkoMC** [comment]
You don't use that or you leaked your token elsewhere and it was in plain text.

**Comment by FireFlyButBlue** [comment]
yes i use that and i do not leak my tokens plain text nevermind

**Comment by IMarkoMC** [comment]
Surely you don't leak it lmfao

how did i find it then? 

Anyways this is a waste of time. Locked
