### ISSUE TITLE
lmao

### ISSUE THREAD

**Issue by jakeyjr** [IMarkoMC/Tokens#73]
keep my mf's bot hacked cuz you just hacked a bot that doesnt even work LOL

**Comment by IMarkoMC** [comment]
"You hacked". Do you know how to read m8?

**Comment by jakeyjr** [comment]
why is tagged angry skid im happy that u hacked it

**Comment by IMarkoMC** [comment]
> hacked it

Do you know how to read? If you know how to read go read the readme so you understand what this repo is and how we found your token.

**Comment by jakeyjr** [comment]
i did why you so angry i know you didnt hack it you stole my token and posted it i completly understand that i should not do that again

**Comment by jakeyjr** [comment]
Damn i meant to say u found it

**Comment by IMarkoMC** [comment]
>  you stole my token

https://github.com/IMarkoMC/Tokens#faq

**Comment by jakeyjr** [comment]
bro i said u found my token

**Comment by skidmaster69420** [comment]
Date: 20.12.2022

Hello there,

I have got some news. But first off, the token was publicly accessible, hence it was rendered useless to prevent your bot being abused. You can always generate a token, just ensure to store it somewhere that is NOT publicly accessible like a [ENV](https://github.com/IMarkoMC/Tokens/tree/main/how_to_use_env). 

Now for the News, when the police picked me up in their police car and drove me to the station, I lost all will to resist and confessed everything I knew about BOSS while still in the Car. I told them that BOSS was in Spain discussing his Automobile Part Manufacturing Counterfeiting Ring with his co-conspirators Stanley and Bruno. He wants to make all cars except for his own inferior and downright useless to have the best car of all. 

They told me they'd be going after him soon. BOSS if you read this, you have to understand they were going to break Miku. I am also upset that you didn't use the tracker you had installed in my car to monitor me to locate my stolen car.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
