### ISSUE TITLE
bruh 

### ISSUE THREAD

**Issue by Sarthepro** [IMarkoMC/Tokens#75]
You somehow reset my bots token >:( I was making a testing bot and you made discord reset my bots token somehow
![9A0D404D-7C37-4BCD-AB0B-5AF5EBBC2E84](https://user-images.githubusercontent.com/83338830/210323976-64552579-2f2e-440b-9f6b-ad3fff16f233.jpeg)

**Comment by IMarkoMC** [comment]
YoU sOmEhOw ReSet mY bOt ToKeN

Learn how to read. 
"Be more careful in the future, and make sure to not accidentally upload your token publicly!"

**Comment by Sarthepro** [comment]
No I didnt post it? I always have my tokens in a .env

**Comment by IMarkoMC** [comment]
Surely lmfao

If you don't leak it how did i get it?

**Comment by IMarkoMC** [comment]
i AlWaYs uSe EnV 
![image](https://user-images.githubusercontent.com/44303652/210649399-5843cabf-704a-48ed-8743-b3bc6cda8b28.png)

**Comment by skidmaster69420** [comment]
Date: 29.12.2022

Hello there,

as of 29.12.2022 at 4:20pm in Madrid, Spain. BOSS has been arrested, he now remains with the Spanish Authorities. He's currently still in questioning, the company is still on vacation. So I am unsure how SKIDMASTER69420 LLC. will proceed without BOSS, but we'll have to see. The future remains unsure for now, the flies seem to think that they'll manage, I still have access to the Chatrooms for some reason. I am unsure what will happen to me, if I'll be employed again or if they never wish to see me again. But I had to do it, for Miku.

Yours,
Unpaid Intern
