### ISSUE TITLE
Unfunny skid

### ISSUE THREAD

**Issue by heyadisco** [IMarkoMC/Tokens#76]

**Comment by IMarkoMC** [comment]
Cry harder skid

**Comment by heyadisco** [comment]
> Cry harder skid

Me? Skid? You must be joking 🤣

**Comment by IMarkoMC** [comment]
You're the one hosting skidded things in public hosting services lmfao

Cry harder skid.

**Comment by IMarkoMC** [comment]
> you should think again "how did this happen"

You're asking way too much from a 12yo that cannot code shit and the only thing he knows how to do is create a GitHub account and cry in repos because he has no skill to code and the only thing he can do is copy and paste code
