### ISSUE TITLE
Stay mad, skiddo.

### ISSUE THREAD

**Issue by heyadisco** [IMarkoMC/Tokens#77]
Actually I never leaked my token, because I'm not stupid. However, this repository is useless and maybe you should reconsider how you're spending your limited time on this planet (_inconveniencing people who are new to developing Discord bots_)

**Comment by IMarkoMC** [comment]
"Stay mad skiddo" lmfao

Imagine being a skid and calling other real developers skids 

Skids never fail to amaze me.

Cry harder idiot

**Comment by IMarkoMC** [comment]
Your and all other skid tears are greatly appreciated over here. 

Continue hosting skidded things so i can nuke your bots

**Comment by IMarkoMC** [comment]
"because I'm not stupid"

Lmfao imagine claiming you have IQ skid.

Anyways I'm not wasting time with a idiot like you

Go cry to your mom

**Comment by IMarkoMC** [comment]
"(inconveniencing people who are new to developing Discord bots)"

Do a favor to all real developers and go learn how to properly store secrets and then open issues in a repo skid

**Comment by eric48906** [comment]
> "(inconveniencing people who are new to developing Discord bots)"
> 
> Do a favor to all real developers and go learn how to properly store secrets and then open issues in a repo skid

Marko, I'm pretty sure you're delusional. Didn't he clearly state that he never leaked his token? Anyways, I agree @heyadisco

**Comment by eric48906** [comment]
> > "(inconveniencing people who are new to developing Discord bots)"
> > Do a favor to all real developers and go learn how to properly store secrets and then open issues in a repo skid
> 
> Marko, I'm pretty sure you're delusional. Didn't he clearly state that he never leaked his token? Anyways, I agree @heyadisco

Forgot to mention, I meant "a delusional skid", hahaha.

**Comment by IMarkoMC** [comment]
Lmfao, imagine calling someone a delusional skid

Learn how to code skid
