### ISSUE TITLE
unasked for

### ISSUE THREAD

**Issue by DertexNeverArrived** [IMarkoMC/Tokens#79]
today, I spent 2 hours working on my new bot and when I finally finished it, I went home when I got home, I got sent a message from discord that my token got doxxed and that it reset. now whatever I do, the bot doesn't work anymore even when I replace the token in the code and so because of this bs, 2 hours of my life were wasted

**Comment by IMarkoMC** [comment]
Token got doxxed lmfao

> even when I replace the token in the code

Do NOT store tokens in code. Do things properly and use Environment variables.
