### ISSUE TITLE
I just have a question if you could check what I did or accidentally did maliciously. discord said my token was found here. 

### ISSUE THREAD

**Issue by me505** [IMarkoMC/Tokens#81]

**Comment by IMarkoMC** [comment]
Your token was in plain text and it was publicly accessible.

You should use [Environment variables](https://github.com/IMarkoMC/Tokens/tree/main/how_to_use_env)

**Comment by Actuallybarcode** [comment]
Thanks for finding my token, I was testing something and I assumed I posted it by accident.

**Comment by skidmaster69420** [comment]
Hello there, 

So my court date is soon, I am preparing what suit to wear. I will wear a Pajama to court!
I bet that will impress the Judge and I won't receive Jail time for sending death threats.
Nine Year Olds always send death threats on twitter!!! But NOOO, Only I am punished by the legal system.
So unfair....

Oh and also, you did ask us what you did....
me505, I know what you did when you were 10 years old.
I know damn well, I won't forgive you either.
...that tree still exists, the tree is still recovering.
You are guilty, you know that.
The token is still stapled to the tree to this day.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.

**Comment by me505** [comment]
wtf
