### ISSUE TITLE
thanks dude

### ISSUE THREAD

**Issue by KNOX-ui** [IMarkoMC/Tokens#83]
the world is running out of people like you. never change and have a good one!

**Comment by skidmaster69420** [comment]
Hello there,

So here's an Update, after the FBI has returned all my stuff to me, and after they ignored my attempted murder at a Judge... citing that I am a mental danger to keep in a prison as I would probably cause all inmates to be just as insane, I was placed on house arrest. I log into work via a remote terminal on my PC. On my break times, I play Persona 5, I am now at a very challenging part, I need to chose a dialogue option and simply can't decide!

I know that my dialogues change the story significantly 

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
