### ISSUE TITLE
False use

### ISSUE THREAD

**Issue by ProKocak28** [IMarkoMC/Tokens#84]
This thing made a discord bot's token deleted even if the bot is not even a scamming or phising bot.

**Comment by Die-Antwoord** [comment]
It not about scamming or phishing. 

You leaked your token and it was posted here to let discord deleted it . So no one can use it for ill intent

**Comment by IMarkoMC** [comment]
> This thing made a discord bot's token deleted even if the bot is not even a scamming or phising bot.

Store your token properly lol.

Trying to determine if a token should be pushed or not it's not a option. 
If i find your token in plain text it will be posted, i don't care if it's not a scam

**Comment by skidmaster69420** [comment]
Hello there,

You are right that we used the bot wrong, we wish to apologize sincerely.
Wel'll work on a bot that will erase you next, to correct our mistake. Thank you.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
