### ISSUE TITLE
Thanks! one of my bot tokens was in here

### ISSUE THREAD

**Issue by LiteEagle262** [IMarkoMC/Tokens#87]
![bitmoji](https://sdk.bitmoji.com/render/panel/e6518353-71e9-41b7-9208-fde8f676bf08-23de18f4-5dc2-407d-8721-7214413b2e61-v1.png?transparent=1&palette=1&width=246)

**Comment by skidmaster69420** [comment]
Cringe??!! Is that all you shitposting fucks cay say?! Durr based based based cringe cringe  Based Based Cringe Cringe Based Cringe I Feel Like I’m In a Fucking asylum  Full of dementia Ridden old people That can do nothing  but repeat the same fucking words on loop Like a fucking broken record  Cringe Cringe Cringe Cringe  Cringe based based  Onions Onions Snoyy  Onions Lol Onions Cringe  Boomer  Le zoomer  I am Boomer  Go Zoom Zoom Zoomies  Zoomer Going Zoomies  NNGAAAHHH I Fucking Hate The Internet so God Damn Much Fuck Shitposting Honest To God Fucking Hope your mother chokes on her own feces In hell You Cocksucker But OHHHHHHHHHH I know my post is cringe isn’t it Cringe Cringe Cringy cringe  Based Cringe  Based Reddit Cringe  Based Cringe Zoom Cringe  Onions Cringe Based  REDDIT BASED AHHHHHHHHHHH

![](https://img1.picmix.com/output/pic/normal/9/2/9/4/10554929_79b87.gif)
(Me and your Father at 4am)

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
