### ISSUE TITLE
Uh my bot is just a spotify music bot???

### ISSUE THREAD

**Issue by Rejuiin** [IMarkoMC/Tokens#88]
Why did my token even get here??? 
Also any way I can prevent this from happening again???

**Comment by Die-Antwoord** [comment]
https://github.com/IMarkoMC/Tokens/tree/main/how_to_use_env

> Why did my token even get here??? Also any way I can prevent this from happening again???

**Comment by IMarkoMC** [comment]
> Why did my token even get here???

Because you had the token floating somewhere publicly available in plain text

>  Also any way I can prevent this from happening again???

Use ENV variables

**Comment by Rejuiin** [comment]
Ahh, I see thanks!

**Comment by skidmaster69420** [comment]
Hello there,

STOP THANKING ME.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
