### ISSUE TITLE
Shit invalid tokens

### ISSUE THREAD

**Issue by AreYouMehmetEfeisModder** [IMarkoMC/Tokens#89]
All invalid tokens

**Comment by IMarkoMC** [comment]
What did you expect? Free tokens?
Lmfao

**Comment by Angry-Pineapple3121** [comment]
sorry sir I already used all the tokens and they are all banned
please wait for the next batch of tokens to be pushed within the next 3-5 business days

**Comment by AreYouMehmetEfeisModder** [comment]
yes of course i was waiting for free token xd

**Comment by IMarkoMC** [comment]
Congratulations you misunderstood the whole purpose of this repo!

**Comment by skidmaster69420** [comment]
> yes of course i was waiting for free token xd

Hello there,

I forwarded your request to our hard working token vultures. They seemed upset, said something in an language I can't understand. However they did go to the SKIDMASTER69420 Weaponary, I don't even know why we have those. BOSS had them installed for when the police was to show up... well... the police was quicker than him. Anyway, the vultures are equipped with a----

>**Warning**
ALL INTERNET COMMUNICATION HAS BEEN CUT OFF TO YOUR LOCATION.
300 VULTURES ARE RAPIDLY APPROACHING YOUR LOCATION.
EVACUATE! EVACUATE! EVACUATE!
