### ISSUE TITLE
Retardo NiggaHooker is a music bot who i translated to cz xDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD

### ISSUE THREAD

**Issue by LidlBambi** [IMarkoMC/Tokens#9]
![image1](https://user-images.githubusercontent.com/96979466/184838950-07dea6ff-14ce-4583-aafb-f60a59106066.png)'

my very p host was down and thats why the bot was offline, idk why
if it was nuke bot itll be deleted soooooooooo long
im waiting for apologise & ur discord uid robin hood
![image2](https://user-images.githubusercontent.com/96979466/184839291-fb063f7a-2c92-443f-8d65-f469bd774c59.png)

**Comment by IMarkoMC** [comment]
>  im waiting for apologise & ur discord uid robin hood

You wont get anything. Closing this issue as there's nothing that i need to do

**Comment by skidmaster69420** [comment]
I noticed the bot had a very bad word in it, and i cri. Your bot is as funny as your future. 
Oh... wait. Sorry, I thought you had one.
