### ISSUE TITLE
lol best trick to get toekn

### ISSUE THREAD

**Issue by jven123** [IMarkoMC/Tokens#90]
some people can randomly goto replit and get token for free bcuz the guy didnt secure his token

**Comment by jven123** [comment]
if u didnt secure ur token then ur retarded

**Comment by IMarkoMC** [comment]
People leaking the token in public sites like replit or other file sharing/hosting services is bad but it's worse the amount of stolen accounts you can find in other sites because people run random exes or scan QR codes in discord

**Comment by skidmaster69420** [comment]
Hello there,

Honestly I believe it is rude to refer to innocent people with a slur, sure they made a mistake.
But really, do you need to throw slurs at them? I mean insulting is fine, I do it all the time.
But what do I know, I am just an Unpaid Intern

Also, nothing truly has happened yet. Wonder if I just jinxed myself though.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
