### ISSUE TITLE
Epic

### ISSUE THREAD

**Issue by Neko-Life** [IMarkoMC/Tokens#91]
Such horror looking at how many token you can find. These dummy kid who don't understand how important their auth token is until someone got into their bot account and raid every server it's in. They need to be taught a lesson anyway and probably shouldn't run a discord bot in the first place.

Keep up the good work 👍🏻

**Comment by skidmaster69420** [comment]
Dear Neko-Life,

As the FBI (Fly Bureau of Investigation), we appreciate the compliment you have left for the Company that we have seized.
Please do be aware, that we are planning to release the Person known as Intern, Unpaid as soon as the investigation concludes.
Should this answer not be sufficent, please await the response of Intern, Unpaid. If he chooses to respond to you or not is unknown to us, we simply do our duty.

Thank you regardless.

Sincerely,
The FBI
(Fly Bureau of Investigation.)
Flying, Bullshittery, Intellectually.
