### ISSUE TITLE
🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕

### ISSUE THREAD

**Issue by blu-knite** [IMarkoMC/Tokens#93]
🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕

**Comment by IMarkoMC** [comment]
https://user-images.githubusercontent.com/44303652/214892181-fcb59f4a-964c-45a4-ae6a-2ee9afbeccf7.mp4

**Comment by skidmaster69420** [comment]
Hello there,

Well 🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕, you too!

Fuck you
Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
