### ISSUE TITLE
Discord Token

### ISSUE THREAD

**Issue by PGC-Talha** [IMarkoMC/Tokens#94]
So how were you able to find my discord token, like did you use a web scraper, because it's actually really interesting how my token got leaked as I try my best to keep it secure.

**Comment by Die-Antwoord** [comment]
> So how were you able to find my discord token, like did you use a web scraper, because it's actually really interesting how my token got leaked as I try my best to keep it secure.

You exposed it somewhere publicly . 

You should use .env you can read more here https://github.com/IMarkoMC/Tokens/tree/main/how_to_use_env

**Comment by IMarkoMC** [comment]
>  like did you use a web scraper

I scan various sites for exposed tokens or stolen tokens (Using malware) to invalidate them, as Die-Antwoord said, if you want to keep your token secure you should use env

**Comment by skidmaster69420** [comment]
Hello there,

I am bored. Pikachu.

Pikachu. Oh no.
Pikachu....

For context, pikachu is a serial killer. 
I know it killed my parents after they failed to show up to my 0th birthday.
Well, what should I say, I hate Pikachu from the bottom of my heart, for he
caused me to suffer.

Pikachu... I will murder you.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
