### ISSUE TITLE
MOTHER FUCKER IS ASS

### ISSUE THREAD

**Issue by zacknapYT** [IMarkoMC/Tokens#95]
MOTHER FUCKER YOU ARE ASS AND NO ONE LIKES BITCH SO PLEASE FUCKING DIE LIKE WHO FUCKING SAID TO YOU TO LEAK THEM NO LIKES FUCK YOU

**Comment by Die-Antwoord** [comment]
> MOTHER FUCKER YOU ARE ASS AND NO ONE LIKES BITCH SO PLEASE FUCKING DIE LIKE WHO FUCKING SAID TO YOU TO LEAK THEM NO LIKES FUCK YOU

you leaked it . . .

**Comment by IMarkoMC** [comment]
**Cry harder**

**Comment by User9684** [comment]
sounds like to me that you need your momma

Cope & seethe skid

**Comment by iTzArshia** [comment]
Oh God 🤦🏻‍♂️

**Comment by oahx** [comment]
Bro yall should be happy he just made sure yall discord accounts dont get nuked☠ Y'all some real fucking skids thinking yall got doxxed or sum shit

**Comment by FEEON** [comment]
You just exposed yourself 😂😂

**Comment by skidmaster69420** [comment]
You posted your token on the internet. Get better next time.

k@kitten
(Sorry kitten, I was busy telling people they had a major skill issue on the internet again. Now where was I.)
Can't make it. Can't make it. Shit's stuck. Outta my butt son! SHITS STUCK! SHITS STUCK! I BEG YOU! I'm dead.

**Comment by FEEON** [comment]
that's crazy
