### ISSUE TITLE
Do you use replit? 

### ISSUE THREAD

**Issue by Awashcard0** [IMarkoMC/Tokens#97]
Only place I've seen.env is on replit

**Comment by IMarkoMC** [comment]
No. i don't use Replit and ENV is not a Replit thing, environment variables can be used everywhere

**Comment by skidmaster69420** [comment]
Hello there,

What the fuck is a fucken replit. I am only hired to respond to these issues, so stfu about these fucken replits.
You fucken reptile, you goddamn piece of reptilian garbage, never ever post an issue here again or there will be 
consequences, where I will have your bretheren slaughtered by a reptilian hunter.

Replit, more like get fucken split.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.

**Comment by Awashcard0** [comment]
You saying you're job is to scream a people for no reason? Get a life

**Comment by IMarkoMC** [comment]
> you're job

Huh?!

**Comment by skidmaster69420** [comment]
> You saying you're job is to scream a people for no reason? Get a life

your*

Unpaid Intern
SKIDMASTER69420 LLC.

**Comment by Awashcard0** [comment]
When?

**Comment by IMarkoMC** [comment]
https://user-images.githubusercontent.com/44303652/224508727-1596c08c-e099-4d2d-b5b1-c23bca61da95.mp4
