### ISSUE TITLE
SO how did you manage to get my token 

### ISSUE THREAD

**Issue by CarmineCMD** [IMarkoMC/Tokens#98]
my token was only stored in one place and is in a secure encrypted file. did you pull it from replit?

**Comment by Die-Antwoord** [comment]
encrypted lol. 
You exposed it somewhere publicly .

You should use .env you can read more here https://github.com/IMarkoMC/Tokens/tree/main/how_to_use_env

> my token was only stored in one place and is in a secure encrypted file. did you pull it from replit?

**Comment by IMarkoMC** [comment]
> my token was only stored in one place and is in a secure encrypted file. did you pull it from replit?

If your token is here you or someone leaked it in some way.

I scan a lot of stuff searching for tokens and i won't disclose where i found a specific token.

**Comment by skidmaster69420** [comment]
Hello there,

there is a quite a story to this one. You see Michael, the local town drug dealer meet with Steven, a fucken dumbass. 
Steven then went and called the local dipshit department, its sorta like the police but different. At the dipshit department
people like are you employed, though obviously you as you work for the dumbass department presumably.
The dipshit department then went on the internet and searched "leaked tokens", and they found yours.
So they put it in the shitter, which alerts the token vultures and the rest from then on is history.
