### ISSUE TITLE
kys

### ISSUE THREAD

**Issue by sitehoster22** [IMarkoMC/Tokens#99]
i obfuscated my code u cant do shi now

**Comment by Die-Antwoord** [comment]
> i obfuscated my code u cant do shi now

BHABHABHA you are just bad at keeping your token safe . Learn to read before writing and replying pleb

**Comment by skidmaster69420** [comment]
Hello there, 

It seems you have at the very least learned to type out 3 letters, I believe that is all you are capable of.
You should be ashamed at the resources that you are wasting to sustain the pathetic thing that is your life.
Honestly, quiet frankly, you should be ashamed at the things you have done so far, but there will of course be no 
reflecting coming from your side, you just solely exist to create garbage and make other people your victim. You are the sort of person that is loathed the most, yet you probably don't care as you probably never experienced even an ounce of someone that truly loves you. I believe you could be pittied, but not by me. 

I solely came here to make you regret ever even opening this issue.

No, you are the sort of person to try and find garbage in a trash can only to find out that the only true garbage is looking for garbage. You are the sort of person to never even receive any sort of praise, for you are loathed everywhere.
But on the Internet where you can be anonymous and simply do anything you want without reprucussion? You become the King and believe that you can make others go through hard times.

You truly are beyond merit. You are just some Skid on the internet.
Those 3 letters may make you seem like the triumphant one here, but believe me the only thing you achieved here, 

Is that you managed to show how pathetic you truly are.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
